name: mono_games
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # 状態管理
  flutter_riverpod: 
  riverpod_annotation: 
  hooks_riverpod: 
  flutter_hooks:
  freezed_annotation: 
  json_annotation: 
  slang: 
  slang_flutter: 

  #コード品質管理
  pedantic_mono:

  #UI
  cupertino_icons:
  flex_color_scheme: ^8.4.0
  shared_preferences:
  flame: ^1.35.0
  flame_forge2d: ^0.19.2+3
  sensors_plus: ^7.0.0
  audioplayers: ^6.1.0
  url_launcher: ^6.3.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  # 自動生成
  build_runner:
  riverpod_generator:
  flutter_gen_runner:
  freezed:
  json_serializable:
  envied_generator:
  slang_build_runner:

  # アイコン生成
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

  assets:
    - assets/sounds/noir_mind/

  shaders:
    - shaders/noir_mind/glassmorphism.frag
    - shaders/noir_mind/wireframe.frag
    - shaders/noir_mind/matte.frag
    - shaders/noir_mind/bubble.frag
    - shaders/noir_mind/ice.frag
    - shaders/noir_mind/slate.frag
    - shaders/noir_mind/slime.frag


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf

flutter_launcher_icons:
  android: true
  adaptive_icon_foreground: "assets/logo/logo_android_light.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_monochrome: "assets/logo/logo_android_dark.png"

  ios: true
  image_path_ios: "assets/logo/logo_ios_light.png"
  remove_alpha_ios: true
  image_path_ios_dark_transparent: "assets/logo/logo_ios_dark.png"
  image_path_ios_tinted_grayscale: "assets/logo/logo_ios_light.png"
  desaturate_tinted_to_grayscale_ios: true

flutter_gen:
  output: lib/gen/