#!/usr/bin/env python3
"""英検5級 500語 下書きCSV生成スクリプト"""
import csv, sys

WORDS = [
    # ── 時間 ──────────────────────────────────────────
    ("minute","分","noun","daily"),
    ("hour","時間","noun","daily"),
    ("day","日","noun","daily"),
    ("week","週","noun","daily"),
    ("month","月","noun","daily"),
    ("year","年","noun","daily"),
    ("today","今日","noun","daily"),
    ("weekend","週末","noun","daily"),
    ("morning","朝","noun","daily"),
    ("afternoon","午後","noun","daily"),
    ("evening","晩","noun","daily"),
    ("night","夜","noun","daily"),
    ("midnight","深夜","noun","daily"),
    ("birthday","誕生日","noun","daily"),
    # ── 曜日 ──────────────────────────────────────────
    ("Monday","月曜日","noun","daily"),
    ("Tuesday","火曜日","noun","daily"),
    ("Wednesday","水曜日","noun","daily"),
    ("Thursday","木曜日","noun","daily"),
    ("Friday","金曜日","noun","daily"),
    ("Saturday","土曜日","noun","daily"),
    ("Sunday","日曜日","noun","daily"),
    # ── 月 ────────────────────────────────────────────
    ("January","1月","noun","daily"),
    ("February","2月","noun","daily"),
    ("March","3月","noun","daily"),
    ("April","4月","noun","daily"),
    ("May","5月","noun","daily"),
    ("June","6月","noun","daily"),
    ("July","7月","noun","daily"),
    ("August","8月","noun","daily"),
    ("September","9月","noun","daily"),
    ("October","10月","noun","daily"),
    ("November","11月","noun","daily"),
    ("December","12月","noun","daily"),
    # ── 季節 ──────────────────────────────────────────
    ("spring","春","noun","nature"),
    ("summer","夏","noun","nature"),
    ("autumn","秋","noun","nature"),
    ("fall","秋","noun","nature"),
    ("winter","冬","noun","nature"),
    # ── 場所 (rarejob) ───────────────────────────────
    ("country","国","noun","place"),
    ("place","場所","noun","place"),
    ("station","駅","noun","place"),
    ("airport","空港","noun","place"),
    ("park","公園","noun","place"),
    ("hospital","病院","noun","place"),
    ("store","店","noun","place"),
    ("supermarket","スーパー","noun","place"),
    ("mountain","山","noun","nature"),
    ("sea","海","noun","nature"),
    ("restaurant","レストラン","noun","place"),
    ("home","家","noun","daily"),
    ("house","一軒家","noun","daily"),
    ("room","部屋","noun","daily"),
    ("bedroom","寝室","noun","daily"),
    ("kitchen","台所","noun","daily"),
    ("bathroom","お風呂","noun","daily"),
    ("classroom","教室","noun","daily"),
    ("gym","体育館","noun","place"),
    # ── 天気（名詞）──────────────────────────────────
    ("sun","太陽","noun","nature"),
    ("cloud","雲","noun","nature"),
    ("rain","雨","noun","nature"),
    ("snow","雪","noun","nature"),
    ("fog","霧","noun","nature"),
    ("sunshine","日差し","noun","nature"),
    ("shower","にわか雨","noun","nature"),
    # ── 天気（形容詞）────────────────────────────────
    ("sunny","晴れた","adjective","nature"),
    ("cloudy","曇った","adjective","nature"),
    ("rainy","雨降りの","adjective","nature"),
    ("snowy","雪の降る","adjective","nature"),
    ("foggy","霧の","adjective","nature"),
    ("windy","風の強い","adjective","nature"),
    # ── 人・家族 (rarejob) ────────────────────────────
    ("boy","少年","noun","people"),
    ("girl","少女","noun","people"),
    ("man","男性","noun","people"),
    ("woman","女性","noun","people"),
    ("person","人","noun","people"),
    ("friend","友だち","noun","people"),
    ("parent","親","noun","people"),
    ("brother","兄弟","noun","people"),
    ("sister","姉妹","noun","people"),
    ("grandfather","おじいさん","noun","people"),
    ("grandmother","おばあさん","noun","people"),
    ("cousin","いとこ","noun","people"),
    # ── 職業 (rarejob) ───────────────────────────────
    ("doctor","医者","noun","people"),
    ("driver","運転手","noun","people"),
    ("dancer","ダンサー","noun","people"),
    ("officer","警官","noun","people"),
    ("pianist","ピアニスト","noun","people"),
    ("pilot","パイロット","noun","people"),
    ("player","選手","noun","people"),
    ("singer","歌手","noun","people"),
    ("waiter","ウエーター","noun","people"),
    ("worker","働く人","noun","people"),
    ("job","仕事","noun","people"),
    # ── スポーツ (rarejob) ────────────────────────────
    ("basketball","バスケットボール","noun","people"),
    ("tennis","テニス","noun","people"),
    ("baseball","野球","noun","people"),
    ("soccer","サッカー","noun","people"),
    ("badminton","バドミントン","noun","people"),
    ("surfing","サーフィン","noun","people"),
    ("swimming","水泳","noun","people"),
    ("marathon","マラソン","noun","people"),
    ("boxing","ボクシング","noun","people"),
    # ── その他名詞 (rarejob) ──────────────────────────
    ("dinner","夕食","noun","daily"),
    ("color","色","noun","general"),
    ("family","家族","noun","people"),
    ("flower","花","noun","nature"),
    ("test","テスト","noun","daily"),
    ("drink","飲み物","noun","daily"),
    ("name","名前","noun","general"),
    ("dictionary","辞書","noun","daily"),
    ("passport","パスポート","noun","general"),
    ("homework","宿題","noun","daily"),
    ("animal","動物","noun","nature"),
    ("box","箱","noun","daily"),
    ("watch","腕時計","noun","daily"),
    ("blackboard","黒板","noun","daily"),
    ("tea","お茶","noun","daily"),
    ("calendar","カレンダー","noun","daily"),
    ("shoes","靴","noun","daily"),
    ("umbrella","傘","noun","daily"),
    ("newspaper","新聞","noun","general"),
    ("window","窓","noun","daily"),
    ("hair","髪","noun","daily"),
    ("diary","日記","noun","daily"),
    ("letter","手紙","noun","general"),
    ("wall","壁","noun","daily"),
    ("bird","鳥","noun","nature"),
    ("doll","人形","noun","daily"),
    ("grape","ぶどう","noun","nature"),
    ("camera","カメラ","noun","general"),
    ("mouth","口","noun","daily"),
    ("coin","硬貨","noun","general"),
    ("song","曲","noun","general"),
    ("music","音楽","noun","general"),
    ("garden","庭","noun","nature"),
    ("idea","考え","noun","mind"),
    ("club","クラブ","noun","people"),
    ("art","芸術","noun","general"),
    ("number","数","noun","general"),
    ("history","歴史","noun","general"),
    ("story","物語","noun","general"),
    ("subject","科目","noun","daily"),
    ("plane","飛行機","noun","place"),
    ("bread","パン","noun","daily"),
    ("dish","料理","noun","daily"),
    ("tree","木","noun","nature"),
    ("fish","魚","noun","nature"),
    ("food","食べ物","noun","daily"),
    ("fruit","果物","noun","nature"),
    # ── 動詞 (rarejob) ───────────────────────────────
    ("like","好きだ","verb","action"),
    ("have","持っている","verb","action"),
    ("go","行く","verb","action"),
    ("play","遊ぶ","verb","action"),
    ("want","欲しい","verb","action"),
    ("eat","食べる","verb","action"),
    ("read","読む","verb","action"),
    ("see","見る","verb","action"),
    ("make","作る","verb","action"),
    ("come","来る","verb","action"),
    ("study","勉強する","verb","action"),
    ("get","手に入れる","verb","action"),
    ("take","取る","verb","action"),
    ("write","書く","verb","action"),
    ("work","働く","verb","action"),
    ("use","使う","verb","action"),
    ("drink","飲む","verb","action"),
    ("wash","洗う","verb","action"),
    ("cook","料理する","verb","action"),
    ("speak","話す","verb","action"),
    ("run","走る","verb","action"),
    ("sleep","眠る","verb","action"),
    ("buy","買う","verb","action"),
    ("open","開ける","verb","action"),
    ("swim","泳ぐ","verb","action"),
    ("listen","聴く","verb","action"),
    ("look","見る","verb","action"),
    ("sing","歌う","verb","action"),
    ("know","知っている","verb","action"),
    ("sit","座る","verb","action"),
    ("clean","掃除する","verb","action"),
    ("help","助ける","verb","action"),
    ("meet","会う","verb","action"),
    ("walk","歩く","verb","action"),
    ("ski","スキーをする","verb","action"),
    ("start","始める","verb","action"),
    ("talk","おしゃべりする","verb","action"),
    ("teach","教える","verb","action"),
    ("do","する","verb","action"),
    ("think","考える","verb","action"),
    ("need","必要とする","verb","action"),
    ("close","閉める","verb","action"),
    ("give","あげる","verb","action"),
    ("stop","止まる","verb","action"),
    ("dance","踊る","verb","action"),
    ("love","愛する","verb","action"),
    ("live","住む","verb","action"),
    ("stand","立つ","verb","action"),
    ("wait","待つ","verb","action"),
    ("put","置く","verb","action"),
    ("brush","磨く","verb","action"),
    ("ride","乗る","verb","action"),
    ("camp","キャンプする","verb","action"),
    ("learn","学ぶ","verb","action"),
    ("smile","微笑む","verb","action"),
    ("begin","始まる","verb","action"),
    ("enjoy","楽しむ","verb","action"),
    ("practice","練習する","verb","action"),
    ("drive","運転する","verb","action"),
    ("ask","たずねる","verb","action"),
    ("tell","伝える","verb","action"),
    ("fly","飛ぶ","verb","action"),
    ("jump","跳ぶ","verb","action"),
    ("stay","滞在する","verb","action"),
    ("move","動く","verb","action"),
    ("turn","曲がる","verb","action"),
    ("visit","訪れる","verb","action"),
    ("try","試みる","verb","action"),
    ("watch","見守る","verb","action"),
    # ── 動物 (AI) ────────────────────────────────────
    ("dog","犬","noun","nature"),
    ("cat","猫","noun","nature"),
    ("rabbit","うさぎ","noun","nature"),
    ("horse","馬","noun","nature"),
    ("cow","牛","noun","nature"),
    ("pig","豚","noun","nature"),
    ("sheep","ひつじ","noun","nature"),
    ("chicken","にわとり","noun","nature"),
    ("duck","アヒル","noun","nature"),
    ("mouse","ネズミ","noun","nature"),
    ("elephant","象","noun","nature"),
    ("lion","ライオン","noun","nature"),
    ("tiger","虎","noun","nature"),
    ("bear","クマ","noun","nature"),
    ("monkey","サル","noun","nature"),
    ("panda","パンダ","noun","nature"),
    ("snake","ヘビ","noun","nature"),
    ("frog","カエル","noun","nature"),
    ("butterfly","チョウ","noun","nature"),
    ("dolphin","イルカ","noun","nature"),
    # ── 果物 (AI) ────────────────────────────────────
    ("apple","りんご","noun","nature"),
    ("banana","バナナ","noun","nature"),
    ("orange","オレンジ","noun","nature"),
    ("strawberry","いちご","noun","nature"),
    ("peach","もも","noun","nature"),
    ("watermelon","すいか","noun","nature"),
    ("lemon","レモン","noun","nature"),
    ("cherry","さくらんぼ","noun","nature"),
    ("pineapple","パイナップル","noun","nature"),
    ("melon","メロン","noun","nature"),
    # ── 野菜 (AI) ────────────────────────────────────
    ("tomato","トマト","noun","nature"),
    ("potato","じゃがいも","noun","nature"),
    ("carrot","にんじん","noun","nature"),
    ("onion","たまねぎ","noun","nature"),
    ("lettuce","レタス","noun","nature"),
    # ── 食事・飲み物 (AI) ─────────────────────────────
    ("milk","牛乳","noun","daily"),
    ("juice","ジュース","noun","daily"),
    ("water","水","noun","daily"),
    ("coffee","コーヒー","noun","daily"),
    ("rice","ご飯","noun","daily"),
    ("pizza","ピザ","noun","daily"),
    ("hamburger","ハンバーガー","noun","daily"),
    ("sandwich","サンドウィッチ","noun","daily"),
    ("cake","ケーキ","noun","daily"),
    ("cookie","クッキー","noun","daily"),
    ("soup","スープ","noun","daily"),
    ("salad","サラダ","noun","daily"),
    ("egg","卵","noun","daily"),
    ("meat","肉","noun","daily"),
    ("cheese","チーズ","noun","daily"),
    # ── 体 (AI) ──────────────────────────────────────
    ("eye","目","noun","daily"),
    ("ear","耳","noun","daily"),
    ("nose","鼻","noun","daily"),
    ("hand","手","noun","daily"),
    ("arm","腕","noun","daily"),
    ("leg","脚","noun","daily"),
    ("foot","足","noun","daily"),
    ("face","顔","noun","daily"),
    ("head","頭","noun","daily"),
    ("stomach","お腹","noun","daily"),
    ("finger","指","noun","daily"),
    ("knee","ひざ","noun","daily"),
    ("tooth","歯","noun","daily"),
    ("back","背中","noun","daily"),
    # ── 服 (AI) ──────────────────────────────────────
    ("shirt","シャツ","noun","daily"),
    ("pants","ズボン","noun","daily"),
    ("dress","ドレス","noun","daily"),
    ("jacket","ジャケット","noun","daily"),
    ("coat","コート","noun","daily"),
    ("hat","帽子","noun","daily"),
    ("sock","靴下","noun","daily"),
    ("glove","手袋","noun","daily"),
    ("sweater","セーター","noun","daily"),
    ("skirt","スカート","noun","daily"),
    ("jeans","ジーンズ","noun","daily"),
    # ── 学校・文具 (AI) ──────────────────────────────
    ("school","学校","noun","place"),
    ("class","授業","noun","daily"),
    ("teacher","先生","noun","people"),
    ("student","生徒","noun","people"),
    ("book","本","noun","daily"),
    ("pen","ペン","noun","daily"),
    ("pencil","鉛筆","noun","daily"),
    ("eraser","消しゴム","noun","daily"),
    ("bag","バッグ","noun","daily"),
    ("desk","机","noun","daily"),
    ("chair","椅子","noun","daily"),
    ("notebook","ノート","noun","daily"),
    ("lunch","昼食","noun","daily"),
    # ── 教科 (AI) ────────────────────────────────────
    ("math","数学","noun","daily"),
    ("science","理科","noun","daily"),
    ("English","英語","noun","general"),
    # ── 場所（追加）(AI) ──────────────────────────────
    ("city","都市","noun","place"),
    ("town","町","noun","place"),
    ("village","村","noun","place"),
    ("street","通り","noun","place"),
    ("road","道路","noun","place"),
    ("hotel","ホテル","noun","place"),
    ("beach","ビーチ","noun","nature"),
    ("museum","博物館","noun","place"),
    ("zoo","動物園","noun","place"),
    ("cinema","映画館","noun","place"),
    ("library","図書館","noun","place"),
    ("pool","プール","noun","place"),
    # ── 自然（追加）(AI) ──────────────────────────────
    ("lake","湖","noun","nature"),
    ("river","川","noun","nature"),
    ("sky","空","noun","nature"),
    ("star","星","noun","nature"),
    ("moon","月","noun","nature"),
    ("earth","地球","noun","nature"),
    ("forest","森","noun","nature"),
    ("island","島","noun","nature"),
    ("grass","草","noun","nature"),
    ("leaf","葉","noun","nature"),
    ("stone","石","noun","nature"),
    ("fire","火","noun","nature"),
    ("ice","氷","noun","nature"),
    ("air","空気","noun","nature"),
    ("light","光","noun","nature"),
    ("seed","種","noun","nature"),
    ("rose","バラ","noun","nature"),
    # ── 交通 (AI) ────────────────────────────────────
    ("bus","バス","noun","place"),
    ("train","電車","noun","place"),
    ("car","車","noun","place"),
    ("bike","自転車","noun","place"),
    ("ship","船","noun","place"),
    ("taxi","タクシー","noun","place"),
    ("ticket","切符","noun","general"),
    # ── 家・家具 (AI) ─────────────────────────────────
    ("door","ドア","noun","daily"),
    ("table","テーブル","noun","daily"),
    ("bed","ベッド","noun","daily"),
    ("sofa","ソファー","noun","daily"),
    ("lamp","ランプ","noun","daily"),
    ("clock","時計","noun","daily"),
    ("phone","電話","noun","daily"),
    ("computer","コンピュータ","noun","general"),
    ("television","テレビ","noun","daily"),
    ("radio","ラジオ","noun","daily"),
    ("key","鍵","noun","daily"),
    ("floor","床","noun","daily"),
    # ── 家族（追加）(AI) ──────────────────────────────
    ("father","父","noun","people"),
    ("mother","母","noun","people"),
    ("son","息子","noun","people"),
    ("daughter","娘","noun","people"),
    ("baby","赤ちゃん","noun","people"),
    ("uncle","叔父","noun","people"),
    ("aunt","叔母","noun","people"),
    ("husband","夫","noun","people"),
    ("wife","妻","noun","people"),
    # ── レジャー (AI) ─────────────────────────────────
    ("game","ゲーム","noun","general"),
    ("sport","スポーツ","noun","people"),
    ("ball","ボール","noun","general"),
    ("team","チーム","noun","people"),
    ("match","試合","noun","people"),
    ("hobby","趣味","noun","people"),
    ("vacation","休暇","noun","daily"),
    ("holiday","祝日","noun","daily"),
    ("trip","旅行","noun","place"),
    ("party","パーティー","noun","people"),
    # ── よく使う名詞（追加）(AI) ──────────────────────
    ("money","お金","noun","general"),
    ("price","値段","noun","general"),
    ("shop","お店","noun","place"),
    ("market","市場","noun","place"),
    ("bridge","橋","noun","place"),
    ("breakfast","朝食","noun","daily"),
    ("message","メッセージ","noun","general"),
    ("gift","贈り物","noun","people"),
    ("map","地図","noun","place"),
    ("flag","旗","noun","general"),
    ("sugar","砂糖","noun","daily"),
    ("salt","塩","noun","daily"),
    # ── 形容詞 (AI) ──────────────────────────────────
    ("big","大きい","adjective","general"),
    ("small","小さい","adjective","general"),
    ("old","古い","adjective","general"),
    ("new","新しい","adjective","general"),
    ("long","長い","adjective","general"),
    ("short","短い","adjective","general"),
    ("tall","背が高い","adjective","general"),
    ("high","高い","adjective","general"),
    ("low","低い","adjective","general"),
    ("fast","速い","adjective","general"),
    ("slow","遅い","adjective","general"),
    ("good","良い","adjective","general"),
    ("bad","悪い","adjective","general"),
    ("hot","暑い","adjective","general"),
    ("cold","寒い","adjective","general"),
    ("warm","暖かい","adjective","general"),
    ("cool","涼しい","adjective","general"),
    ("beautiful","美しい","adjective","general"),
    ("pretty","きれいな","adjective","general"),
    ("cute","かわいい","adjective","general"),
    ("happy","幸せな","adjective","mind"),
    ("sad","悲しい","adjective","mind"),
    ("angry","怒った","adjective","mind"),
    ("tired","疲れた","adjective","mind"),
    ("hungry","お腹が空いた","adjective","daily"),
    ("thirsty","のどが渇いた","adjective","daily"),
    ("sick","病気の","adjective","daily"),
    ("busy","忙しい","adjective","daily"),
    ("free","暇な","adjective","daily"),
    ("easy","簡単な","adjective","general"),
    ("difficult","難しい","adjective","general"),
    ("soft","柔らかい","adjective","general"),
    ("dirty","汚い","adjective","general"),
    ("right","正しい","adjective","general"),
    ("wrong","間違った","adjective","general"),
    ("same","同じ","adjective","general"),
    ("different","違う","adjective","general"),
    ("ready","準備ができた","adjective","general"),
    ("late","遅い","adjective","daily"),
    ("early","早い","adjective","daily"),
    # ── 動詞（追加）(AI) ──────────────────────────────
    ("show","見せる","verb","action"),
    ("find","見つける","verb","action"),
    ("bring","持ってくる","verb","action"),
    ("call","電話する","verb","action"),
    ("carry","運ぶ","verb","action"),
    ("change","変える","verb","action"),
    ("check","確認する","verb","action"),
    ("choose","選ぶ","verb","action"),
    ("cut","切る","verb","action"),
    ("decide","決める","verb","action"),
    ("draw","描く","verb","action"),
    ("feel","感じる","verb","action"),
    ("finish","終える","verb","action"),
    ("hear","聞こえる","verb","action"),
    ("hit","打つ","verb","action"),
    ("hold","持つ","verb","action"),
    ("hope","望む","verb","action"),
    ("join","参加する","verb","action"),
    ("keep","保つ","verb","action"),
    ("leave","去る","verb","action"),
    ("lose","失う","verb","action"),
    ("return","戻る","verb","action"),
    ("save","救う","verb","action"),
    ("say","言う","verb","action"),
    ("send","送る","verb","action"),
    # ── 追加名詞・形容詞 (AI) ──────────────────────────
    ("weather","天気","noun","nature"),
    ("wind","風","noun","nature"),
    ("storm","嵐","noun","nature"),
    ("thunder","雷","noun","nature"),
    ("knife","ナイフ","noun","daily"),
    ("fork","フォーク","noun","daily"),
    ("spoon","スプーン","noun","daily"),
    ("plate","皿","noun","daily"),
    ("cup","カップ","noun","daily"),
    ("album","アルバム","noun","general"),
    ("concert","コンサート","noun","general"),
    ("movie","映画","noun","general"),
    ("magazine","雑誌","noun","general"),
    ("novel","小説","noun","general"),
    ("dream","夢","noun","mind"),
    ("wish","願い","noun","mind"),
    ("memory","思い出","noun","mind"),
    ("feeling","気持ち","noun","mind"),
    ("wood","木材","noun","nature"),
    ("paper","紙","noun","daily"),
    ("race","レース","noun","people"),
    ("jungle","ジャングル","noun","nature"),
    ("desert","砂漠","noun","nature"),
    ("valley","谷","noun","nature"),
    ("wing","翼","noun","nature"),
    ("ruler","定規","noun","daily"),
    ("uniform","制服","noun","daily"),
    ("cap","キャップ","noun","daily"),
    ("ring","指輪","noun","daily"),
    ("accident","事故","noun","general"),
    ("adventure","冒険","noun","general"),
    ("character","キャラクター","noun","general"),
    ("chance","チャンス","noun","general"),
    ("chocolate","チョコレート","noun","daily"),
    ("culture","文化","noun","general"),
    ("exercise","運動","noun","daily"),
    ("interest","興味","noun","mind"),
    ("language","言語","noun","general"),
    ("life","生活","noun","daily"),
    ("nature","自然","noun","nature"),
    ("problem","問題","noun","general"),
    ("question","質問","noun","general"),
    ("answer","答え","noun","general"),
    ("age","年齢","noun","general"),
    ("size","サイズ","noun","general"),
    ("surprise","驚き","noun","mind"),
    ("fun","楽しさ","noun","mind"),
    ("win","勝つ","verb","action"),
    ("picture","写真","noun","daily"),
]

def main():
    out = sys.argv[1] if len(sys.argv) > 1 else "tools/draft_eiken5_replace.csv"
    seen = set()
    rows = []
    for en, ja, pos, theme in WORDS:
        key = en.lower()
        if key in seen:
            print(f"⚠ dup skipped: {en}", file=sys.stderr)
            continue
        seen.add(key)
        rows.append({"id": len(rows)+1, "en": en, "ja": ja, "pos": pos, "theme": theme, "level": "eiken5", "notes": ""})

    with open(out, "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=["id","en","ja","pos","theme","level","notes"])
        w.writeheader()
        w.writerows(rows)

    by_pos = {}
    for r in rows:
        by_pos[r["pos"]] = by_pos.get(r["pos"], 0) + 1
    print(f"✅ 生成完了: {len(rows)} 語 → {out}")
    print(f"   品詞内訳: {dict(sorted(by_pos.items()))}")

if __name__ == "__main__":
    main()
