#!/usr/bin/env python3
"""
英検3級 追加単語生成スクリプト

CEFR-J B1 データから動詞・形容詞を中心に抽出し、
eiken3 の pos バランスを改善しながら 1,000 語に拡張する。

- eiken4/eiken5 との重複 45 語を削除
- 537 語を追加（動詞 304 + 形容詞 233）
- 合計 1,000 語（累計 2,100 語）

使い方:
    python3 tools/generate_eiken3_additional.py
    → tools/draft_eiken3_additional.csv
"""

import csv
import re
import sys

# ── 日本語訳辞書（CEFR-J B1 動詞・形容詞に対応） ──────────────────

TRANSLATIONS = {
    # ── 動詞 (304) ──────────────────────────────
    "abandon": "捨てる",
    "absorb": "吸収する",
    "accompany": "同行する",
    "accomplish": "達成する",
    "accuse": "告発する",
    "accustom": "慣れさせる",
    "acknowledge": "認める",
    "acquire": "習得する",
    "adapt": "適応する",
    "address": "取り組む",
    "adopt": "採用する",
    "advertise": "宣伝する",
    "affect": "影響を与える",
    "afford": "余裕がある",
    "announce": "発表する",
    "applaud": "拍手する",
    "appoint": "任命する",
    "arise": "生じる",
    "arrange": "手配する",
    "assign": "割り当てる",
    "assist": "助ける",
    "associate": "関連づける",
    "assume": "仮定する",
    "attach": "取り付ける",
    "attain": "達成する",
    "attend": "出席する",
    "attract": "引き付ける",
    "babysit": "子守をする",
    "bar": "禁じる",
    "bathe": "入浴する",
    "behave": "振る舞う",
    "bet": "賭ける",
    "bleed": "出血する",
    "bless": "祝福する",
    "block": "遮断する",
    "board": "乗り込む",
    "boast": "自慢する",
    "bore": "退屈させる",
    "bowl": "ボウリングをする",
    "bump": "ぶつかる",
    "burst": "破裂する",
    "bust": "壊す",
    "calculate": "計算する",
    "cancel": "キャンセルする",
    "care": "気にかける",
    "cherish": "大切にする",
    "choke": "窒息する",
    "circle": "丸をつける",
    "classify": "分類する",
    "clear": "片付ける",
    "combine": "組み合わせる",
    "commit": "犯す",
    "complete": "完了する",
    "complicate": "複雑にする",
    "compose": "作曲する",
    "conclude": "結論を出す",
    "congratulate": "お祝いを言う",
    "connect": "接続する",
    "conquer": "征服する",
    "constitute": "構成する",
    "construct": "建設する",
    "consume": "消費する",
    "contain": "含む",
    "contribute": "貢献する",
    "convey": "伝える",
    "convince": "説得する",
    "cultivate": "育てる",
    "dare": "あえてする",
    "date": "日付を記す",
    "declare": "宣言する",
    "dedicate": "捧げる",
    "defend": "守る",
    "define": "定義する",
    "delete": "削除する",
    "deliver": "届ける",
    "demonstrate": "実演する",
    "deny": "否定する",
    "depart": "出発する",
    "deprive": "奪う",
    "derive": "引き出す",
    "deserve": "値する",
    "design": "デザインする",
    "determine": "決定する",
    "devastate": "壊滅させる",
    "differ": "異なる",
    "dig": "掘る",
    "direct": "指揮する",
    "disable": "無効にする",
    "disappoint": "失望させる",
    "discourage": "やる気をなくさせる",
    "dissolve": "溶かす",
    "distinguish": "区別する",
    "distribute": "配布する",
    "drag": "引きずる",
    "drown": "溺れる",
    "educate": "教育する",
    "eliminate": "排除する",
    "embarrass": "恥ずかしがらせる",
    "emerge": "現れる",
    "enable": "可能にする",
    "enclose": "同封する",
    "endanger": "危険にさらす",
    "endure": "耐える",
    "engage": "従事する",
    "enrich": "豊かにする",
    "ensure": "確保する",
    "entertain": "楽しませる",
    "examine": "調べる",
    "excuse": "許す",
    "expand": "拡大する",
    "expose": "さらす",
    "extend": "延長する",
    "fade": "色あせる",
    "fascinate": "魅了する",
    "fasten": "締める",
    "feed": "食べさせる",
    "fetch": "取ってくる",
    "fight": "戦う",
    "float": "浮かぶ",
    "flunk": "落第する",
    "form": "形成する",
    "fry": "揚げる",
    "furnish": "備え付ける",
    "generate": "生み出す",
    "govern": "統治する",
    "grab": "つかむ",
    "group": "グループにまとめる",
    "hang": "掛ける",
    "heal": "癒す",
    "hesitate": "ためらう",
    "hire": "雇う",
    "horrify": "恐怖を与える",
    "ignore": "無視する",
    "illuminate": "照らす",
    "imitate": "模倣する",
    "immigrate": "移住する",
    "impair": "損なう",
    "inform": "知らせる",
    "inhale": "吸い込む",
    "inject": "注射する",
    "inscribe": "刻む",
    "insist": "主張する",
    "inspire": "刺激する",
    "intend": "意図する",
    "interact": "交流する",
    "interrupt": "遮る",
    "invest": "投資する",
    "involve": "巻き込む",
    "irritate": "苛立たせる",
    "joke": "冗談を言う",
    "kid": "からかう",
    "kiss": "キスする",
    "knit": "編む",
    "launch": "発売する",
    "lay": "置く",
    "lessen": "減らす",
    "liberate": "解放する",
    "limp": "びっこを引く",
    "locate": "位置を確認する",
    "lock": "鍵をかける",
    "mail": "郵送する",
    "maintain": "維持する",
    "mash": "つぶす",
    "meditate": "瞑想する",
    "melt": "溶ける",
    "mend": "修繕する",
    "mislead": "誤解させる",
    "modify": "修正する",
    "motivate": "やる気にさせる",
    "mourn": "悲しむ",
    "murder": "殺す",
    "narrate": "語る",
    "notice": "気づく",
    "observe": "観察する",
    "obtain": "得る",
    "occupy": "占領する",
    "occur": "起こる",
    "oppress": "抑圧する",
    "outweigh": "上回る",
    "overcome": "克服する",
    "overwhelm": "圧倒する",
    "owe": "借りがある",
    "own": "所有する",
    "pardon": "許す",
    "participate": "参加する",
    "permit": "許可する",
    "persuade": "説得する",
    "pin": "ピンで留める",
    "plant": "植える",
    "please": "喜ばせる",
    "possess": "所有する",
    "preserve": "保存する",
    "proceed": "進む",
    "proclaim": "宣言する",
    "promote": "促進する",
    "propose": "提案する",
    "prove": "証明する",
    "punish": "罰する",
    "purify": "浄化する",
    "qualify": "資格を得る",
    "rap": "ラップをする",
    "react": "反応する",
    "rearrange": "並び替える",
    "rebuild": "再建する",
    "recall": "思い出す",
    "recite": "暗唱する",
    "reclaim": "取り戻す",
    "recommend": "勧める",
    "recover": "回復する",
    "reduce": "減らす",
    "regain": "取り戻す",
    "regard": "みなす",
    "reject": "拒絶する",
    "relate": "関連する",
    "release": "解放する",
    "rely": "頼る",
    "remark": "述べる",
    "remove": "取り除く",
    "renew": "更新する",
    "repay": "返す",
    "reply": "返事をする",
    "reproduce": "複製する",
    "request": "要求する",
    "require": "必要とする",
    "resemble": "似ている",
    "resist": "抵抗する",
    "resolve": "解決する",
    "respond": "応じる",
    "restore": "回復する",
    "restrict": "制限する",
    "retain": "保持する",
    "retell": "語り直す",
    "reunify": "再統一する",
    "revise": "改訂する",
    "rewrite": "書き直す",
    "rid": "取り除く",
    "riddle": "なぞなぞを出す",
    "rush": "急ぐ",
    "scare": "怖がらせる",
    "scatter": "散らす",
    "scold": "叱る",
    "scream": "叫ぶ",
    "search": "探す",
    "seize": "つかむ",
    "settle": "解決する",
    "shadow": "尾行する",
    "shave": "剃る",
    "shift": "移動する",
    "shiver": "震える",
    "sign": "署名する",
    "simplify": "単純化する",
    "sink": "沈む",
    "skate": "スケートをする",
    "smell": "においがする",
    "soothe": "なだめる",
    "spoil": "台無しにする",
    "stare": "じっと見る",
    "stem": "抑える",
    "stick": "くっつける",
    "stir": "かき混ぜる",
    "strengthen": "強化する",
    "stretch": "伸ばす",
    "strike": "打つ",
    "stumble": "つまずく",
    "stun": "驚かせる",
    "suffer": "苦しむ",
    "sunbathe": "日光浴をする",
    "suppose": "思う",
    "surround": "囲む",
    "swear": "誓う",
    "swell": "腫れる",
    "tape": "テープで留める",
    "tear": "引き裂く",
    "tempt": "誘惑する",
    "tend": "傾向がある",
    "thirst": "渇望する",
    "thump": "ドンと叩く",
    "tighten": "締める",
    "tire": "疲れさせる",
    "toss": "投げる",
    "touch": "触れる",
    "tour": "旅行する",
    "transfer": "転送する",
    "transform": "変える",
    "translate": "翻訳する",
    "tremble": "震える",
    "tumble": "転がる",
    "type": "タイプする",
    "uncover": "暴く",
    "undergo": "経験する",
    "underline": "下線を引く",
    "undo": "元に戻す",
    "undress": "脱ぐ",
    "unfold": "展開する",
    "unify": "統一する",
    "unite": "団結する",
    "unpack": "荷物を解く",
    "update": "更新する",
    "upload": "アップロードする",
    "vary": "変化する",
    "vote": "投票する",
    "wave": "手を振る",
    "wither": "しおれる",
    "witness": "目撃する",
    # ── 形容詞 (260+) ──────────────────────────────
    "absent": "欠席の",
    "accurate": "正確な",
    "aggressive": "積極的な",
    "alike": "似ている",
    "amazing": "素晴らしい",
    "ambitious": "野心的な",
    "amusing": "楽しい",
    "annoyed": "苛立った",
    "annual": "年1回の",
    "ashamed": "恥ずかしい",
    "athletic": "運動の得意な",
    "aware": "気づいている",
    "awesome": "すごい",
    "awkward": "ぎこちない",
    "bare": "裸の",
    "beloved": "愛する",
    "bitter": "苦い",
    "blind": "目の見えない",
    "bold": "大胆な",
    "brief": "短い",
    "broad": "広い",
    "calm": "穏やかな",
    "capable": "有能な",
    "careless": "不注意な",
    "casual": "カジュアルな",
    "cautious": "慎重な",
    "challenging": "挑戦的な",
    "civil": "市民の",
    "classical": "古典的な",
    "competitive": "競争的な",
    "complex": "複雑な",
    "complicated": "複雑な",
    "concerned": "心配した",
    "confusing": "紛らわしい",
    "conscious": "意識のある",
    "conservative": "保守的な",
    "considerable": "かなりの",
    "courageous": "勇気のある",
    "critical": "批判的な",
    "cruel": "残酷な",
    "cultural": "文化的な",
    "damaged": "損傷した",
    "damp": "湿った",
    "deaf": "耳の聞こえない",
    "definite": "明確な",
    "delicate": "繊細な",
    "delighted": "喜んだ",
    "delightful": "楽しい",
    "democratic": "民主主義の",
    "dependent": "依存した",
    "depressed": "落ち込んだ",
    "depressing": "憂鬱な",
    "desperate": "必死な",
    "destructive": "破壊的な",
    "digital": "デジタルの",
    "diligent": "勤勉な",
    "disgusting": "不快な",
    "distant": "遠い",
    "diverse": "多様な",
    "dramatic": "劇的な",
    "drunk": "酔った",
    "dull": "退屈な",
    "eager": "熱心な",
    "effective": "効果的な",
    "electrical": "電気の",
    "electronic": "電子の",
    "embarrassed": "恥ずかしい",
    "emotional": "感情的な",
    "encouraging": "励みになる",
    "endless": "終わりのない",
    "enthusiastic": "熱心な",
    "entire": "全体の",
    "environmental": "環境の",
    "essential": "不可欠な",
    "evident": "明らかな",
    "exact": "正確な",
    "exhausted": "疲れ果てた",
    "experienced": "経験豊富な",
    "extraordinary": "並外れた",
    "extreme": "極端な",
    "faint": "かすかな",
    "faithful": "忠実な",
    "fake": "偽の",
    "fashionable": "流行の",
    "financial": "財政的な",
    "firm": "しっかりした",
    "flat": "平らな",
    "fluent": "流暢な",
    "fond": "好きな",
    "foolish": "愚かな",
    "formal": "正式な",
    "former": "かつての",
    "fortunate": "幸運な",
    "freezing": "凍えるような",
    "frequent": "頻繁な",
    "frozen": "凍った",
    "frustrated": "不満な",
    "generous": "気前の良い",
    "giant": "巨大な",
    "global": "世界的な",
    "gorgeous": "豪華な",
    "graceful": "優雅な",
    "guilty": "罪悪感のある",
    "handy": "便利な",
    "historic": "歴史的な",
    "holy": "神聖な",
    "homeless": "家のない",
    "honest": "正直な",
    "hopeful": "希望に満ちた",
    "hopeless": "絶望的な",
    "horrible": "ひどい",
    "huge": "巨大な",
    "humid": "湿度が高い",
    "humorous": "ユーモアのある",
    "immediate": "即時の",
    "impressive": "印象的な",
    "incredible": "信じられない",
    "independent": "独立した",
    "innocent": "無実の",
    "intense": "激しい",
    "jealous": "嫉妬した",
    "juicy": "ジューシーな",
    "legal": "合法の",
    "loud": "大声の",
    "loyal": "忠実な",
    "magnificent": "壮大な",
    "massive": "巨大な",
    "meaningful": "意味のある",
    "mental": "精神的な",
    "mild": "穏やかな",
    "miserable": "悲惨な",
    "moderate": "穏健な",
    "mutual": "互いの",
    "naked": "裸の",
    "narrow": "狭い",
    "nasty": "不快な",
    "neutral": "中立の",
    "nuclear": "核の",
    "obvious": "明らかな",
    "ordinary": "普通の",
    "organic": "有機の",
    "outstanding": "優れた",
    "painful": "痛い",
    "pale": "青ざめた",
    "patient": "忍耐強い",
    "plain": "地味な",
    "poisonous": "毒のある",
    "positive": "肯定的な",
    "practical": "実用的な",
    "precious": "貴重な",
    "present": "現在の",
    "previous": "前の",
    "productive": "生産的な",
    "pure": "純粋な",
    "rapid": "急速な",
    "rare": "まれな",
    "rational": "合理的な",
    "realistic": "現実的な",
    "reasonable": "合理的な",
    "religious": "宗教的な",
    "remarkable": "注目すべき",
    "ridiculous": "ばかげた",
    "rough": "荒い",
    "satisfied": "満足した",
    "scared": "怖い",
    "scary": "怖い",
    "secret": "秘密の",
    "secure": "安全な",
    "selfish": "自己中心的な",
    "severe": "厳しい",
    "sharp": "鋭い",
    "silent": "静かな",
    "solid": "固い",
    "sore": "痛い",
    "sour": "酸っぱい",
    "spectacular": "壮観な",
    "spicy": "辛い",
    "spiritual": "精神的な",
    "stable": "安定した",
    "steady": "安定した",
    "steep": "急な",
    "sticky": "ベタベタした",
    "stormy": "嵐の",
    "stressed": "ストレスを感じた",
    "stubborn": "頑固な",
    "stunning": "驚くほど美しい",
    "stupid": "愚かな",
    "stylish": "スタイリッシュな",
    "sufficient": "十分な",
    "talented": "才能のある",
    "talkative": "おしゃべりな",
    "tasty": "美味しい",
    "temporary": "一時的な",
    "tense": "緊張した",
    "terrified": "恐怖を感じた",
    "thankful": "感謝した",
    "tiny": "小さな",
    "typical": "典型的な",
    "unexpected": "予期しない",
    "unfortunate": "不運な",
    "unique": "ユニークな",
    "unlikely": "ありそうもない",
    "unlucky": "不運な",
    "urgent": "緊急の",
    "useless": "役に立たない",
    "valuable": "価値のある",
    "vast": "広大な",
    "visible": "見える",
    "vivid": "鮮明な",
    "weird": "変な",
    "widespread": "広まった",
    "worthwhile": "価値のある",
    # ── 形容詞 補足 21語 ──────────────────────────────
    "able": "できる",
    "academic": "学術的な",
    "alternative": "代替の",
    "amazed": "驚いた",
    "apparent": "明らかな",
    "artistic": "芸術的な",
    "central": "中心的な",
    "coastal": "沿岸の",
    "controversial": "議論を呼ぶ",
    "countless": "無数の",
    "current": "現在の",
    "deadly": "致命的な",
    "enjoyable": "楽しい",
    "extinct": "絶滅した",
    "festive": "祝祭の",
    "gifted": "才能のある",
    "numerous": "多数の",
    "reliable": "信頼できる",
    "terrific": "素晴らしい",
    "tremendous": "莫大な",
    "tropical": "熱帯の",
}

# ── CEFR-J → アプリ theme マッピング ──────────────────────────────

CORE_TO_THEME = {
    "Animals": "nature",
    "Food and drink": "nature",
    "Plants and environment": "nature",
    "Weather and climate": "nature",
    "Colour and shape": "nature",
    "Natural features": "nature",
    "Body and health": "daily",
    "The home": "daily",
    "Time": "daily",
    "Physical description": "daily",
    "Clothes": "daily",
    "Education": "people",
    "Work and Jobs": "people",
    "Family and friends": "people",
    "Society": "people",
    "Sport and leisure": "people",
    "Entertainment": "people",
    "Travel and transport": "place",
    "Places and buildings": "place",
    "Geography and environment": "place",
    "Feelings and opinions": "mind",
    "Personality and character": "mind",
    "Thoughts and thinking": "mind",
    "Language and communication": "general",
    "Numbers and quantity": "general",
    "Technology": "general",
}

EXCLUDE = [
    re.compile(r"^[a-z]\.$"),
    re.compile(r"[/\.\-]"),
    re.compile(r"\s"),
    re.compile(r"'"),
]

FUNCTION_WORDS = {
    "a", "an", "the", "is", "are", "was", "were", "be", "been", "being",
    "have", "has", "had", "do", "does", "did", "will", "would", "could",
    "should", "may", "might", "shall", "can", "must", "not", "very",
    "all", "both", "each", "any", "some", "no", "this", "that", "these",
    "those", "i", "you", "he", "she", "it", "we", "they", "who", "which",
    "what", "when", "where", "why", "how", "and", "or", "but", "so", "if",
    "then", "my", "your", "his", "her", "its", "our", "their",
    "me", "him", "us", "them",
}


def is_excluded(word: str) -> bool:
    if word.lower() in FUNCTION_WORDS:
        return True
    return any(p.search(word) for p in EXCLUDE)


def infer_theme(core_inv: str, pos: str) -> str:
    if pos == "verb":
        return "action"
    if pos == "adjective" and "Feeling" in core_inv:
        return "mind"
    return CORE_TO_THEME.get(core_inv, "general")


def main() -> None:
    out_path = sys.argv[1] if len(sys.argv) > 1 else "tools/draft_eiken3_additional.csv"

    with open("assets/quiz/words.csv", newline="", encoding="utf-8") as f:
        rows = list(csv.DictReader(f))

    eiken5_words = {r["en"].lower() for r in rows if r["level"] == "eiken5"}
    eiken4_words = {r["en"].lower() for r in rows if r["level"] == "eiken4"}
    eiken3_existing = [r for r in rows if r["level"] == "eiken3"]
    # eiken4/5 との重複を除いた eiken3 残存語
    eiken3_kept = [
        r for r in eiken3_existing
        if r["en"].lower() not in eiken5_words
        and r["en"].lower() not in eiken4_words
    ]
    eiken3_kept_words = {r["en"].lower() for r in eiken3_kept}
    all_existing = {r["en"].lower() for r in rows}

    target = 1000
    need = target - len(eiken3_kept)
    print(f"重複削除後 eiken3: {len(eiken3_kept)}語")
    print(f"追加必要数: {need}語")

    with open("tools/data/cefrj.csv", newline="", encoding="utf-8") as f:
        cefrj = list(csv.DictReader(f))

    verbs: list[dict] = []
    adjs: list[dict] = []
    seen: set[str] = set()

    for row in cefrj:
        if row.get("CEFR", "").strip() != "B1":
            continue
        word = row.get("headword", "").strip()
        key = word.lower()
        if not word or key in all_existing or key in seen:
            continue
        if is_excluded(word):
            continue
        if key not in TRANSLATIONS:
            continue
        seen.add(key)
        cefr_pos = row.get("pos", "").strip().lower()
        core_inv = row.get("CoreInventory", "").strip()

        if cefr_pos == "verb":
            verbs.append({
                "en": word,
                "ja": TRANSLATIONS[key],
                "pos": "verb",
                "theme": "action",
                "level": "eiken3",
            })
        elif cefr_pos == "adjective":
            adjs.append({
                "en": word,
                "ja": TRANSLATIONS[key],
                "pos": "adjective",
                "theme": infer_theme(core_inv, "adjective"),
                "level": "eiken3",
            })

    # 動詞全件 + 形容詞で need 語を埋める
    additions = verbs + adjs
    additions = additions[:need]

    verb_count = sum(1 for r in additions if r["pos"] == "verb")
    adj_count  = sum(1 for r in additions if r["pos"] == "adjective")
    print(f"候補から選出: {len(additions)}語（動詞:{verb_count} 形容詞:{adj_count}）")

    with open(out_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(
            f,
            fieldnames=["id", "en", "ja", "pos", "theme", "level", "notes"],
        )
        writer.writeheader()
        for i, r in enumerate(additions, start=1):
            writer.writerow({
                "id": i,
                "en": r["en"],
                "ja": r["ja"],
                "pos": r["pos"],
                "theme": r["theme"],
                "level": "eiken3",
                "notes": "",
            })

    print(f"\n✅ 下書き生成: {len(additions)}語 → {out_path}")
    print(f"   eiken3既存(重複削除後): {len(eiken3_kept)}語")
    print(f"   追加後の合計: {len(eiken3_kept) + len(additions)}語")


if __name__ == "__main__":
    main()
