#!/usr/bin/env python3
"""
英検準2級 追加単語生成スクリプト

- eiken5/4/3 との重複 37 語を削除
- CEFR-J B1 残存（形容詞・副詞・名詞）＋ 独自 CANDIDATES 動詞 で拡張
- 目標: 1,100 語（累計 3,200 語）

使い方:
    python3 tools/generate_eiken_pre2_additional.py
    → tools/draft_eiken_pre2_additional.csv
"""

import csv
import re
import sys
from collections import Counter

# ── CEFR-J B1 形容詞・副詞・名詞 の日本語訳 ─────────────────────

TRANSLATIONS_B1: dict[str, str] = {
    # 形容詞
    "abnormal": "異常な",
    "absolute": "絶対的な",
    "abstract": "抽象的な",
    "abundant": "豊富な",
    "accessible": "利用しやすい",
    "accidental": "偶然の",
    "adorable": "可愛い",
    "agricultural": "農業の",
    "allergic": "アレルギーの",
    "animated": "活気のある",
    "bald": "禿げた",
    "bent": "曲がった",
    "bilingual": "バイリンガルの",
    "bound": "行き先の",
    "breathless": "息を切らした",
    "burning": "燃えている",
    "canned": "缶詰の",
    "circular": "円形の",
    "continual": "絶え間ない",
    "continuous": "続く",
    "contrary": "反対の",
    "curly": "カールした",
    "devastating": "壊滅的な",
    "disabled": "障害のある",
    "disastrous": "惨事の",
    "divine": "神聖な",
    "divorced": "離婚した",
    "dusty": "埃っぽい",
    "earnest": "熱心な",
    "eastern": "東の",
    "ecological": "生態学的な",
    "economic": "経済の",
    "engaged": "婚約した",
    "eternal": "永遠の",
    "even": "平らな",
    "exclusive": "独占的な",
    "fallen": "落ちた",
    "faraway": "遠い",
    "forbidden": "禁じられた",
    "future": "将来の",
    "general": "一般的な",
    "genetic": "遺伝の",
    "geographical": "地理的な",
    "glorious": "栄光の",
    "hasty": "急いだ",
    "healing": "癒しの",
    "hearty": "心のこもった",
    "helpless": "無力な",
    "hidden": "隠れた",
    "historical": "歴史的な",
    "imaginary": "想像上の",
    "improper": "不適切な",
    "inconvenient": "不便な",
    "incorrect": "不正確な",
    "indirect": "間接的な",
    "industrial": "産業の",
    "inevitable": "避けられない",
    "informative": "情報豊富な",
    "insane": "正気でない",
    "intensive": "集中的な",
    "intermediate": "中級の",
    "internal": "内部の",
    "involved": "複雑な",
    "irregular": "不規則な",
    "lasting": "永続する",
    "lawful": "合法的な",
    "leading": "主要な",
    "lean": "細い",
    "lifelong": "生涯の",
    "limited": "限られた",
    "liquid": "液体の",
    "literary": "文学の",
    "magical": "魔法の",
    "main": "主な",
    "male": "男の",
    "marine": "海の",
    "marked": "著しい",
    "maximum": "最大の",
    "mechanical": "機械的な",
    "medium": "中程度の",
    "memorable": "印象深い",
    "mere": "単なる",
    "messy": "散らかった",
    "minimum": "最小の",
    "minor": "小さな",
    "misty": "霧がかった",
    "monthly": "月ごとの",
    "motionless": "動かない",
    "narrative": "物語の",
    "nearby": "近くの",
    "newborn": "生まれたばかりの",
    "noticeable": "目立つ",
    "notorious": "悪名高い",
    "nutritious": "栄養のある",
    "occasional": "時々の",
    "offensive": "不快な",
    "oily": "油っぽい",
    "orderly": "整然とした",
    "outdoor": "屋外の",
    "overnight": "一晩の",
    "overwhelming": "圧倒的な",
    "parental": "親の",
    "partial": "部分的な",
    "passive": "受動的な",
    "peculiar": "奇妙な",
    "penniless": "一文無しの",
    "permanent": "永続的な",
    "persuasive": "説得力のある",
    "possessive": "独占欲の強い",
    "pregnant": "妊娠した",
    "primitive": "原始的な",
    "prominent": "著名な",
    "prosperous": "繁栄した",
    "protective": "保護的な",
    "psychological": "心理的な",
    "public": "公共の",
    "qualified": "資格のある",
    "racial": "人種の",
    "recycled": "再利用された",
    "regional": "地域の",
    "relaxing": "リラックスできる",
    "resident": "居住の",
    "residential": "住宅の",
    "respectable": "立派な",
    "ripe": "熟した",
    "rotten": "腐った",
    "sacred": "神聖な",
    "scenic": "景色のよい",
    "shallow": "浅い",
    "shameful": "恥ずかしい",
    "shiny": "輝いている",
    "shocked": "驚いた",
    "shocking": "衝撃的な",
    "spiral": "らせん状の",
    "strategic": "戦略的な",
    "stressful": "ストレスの多い",
    "substantial": "かなりの",
    "superior": "優れた",
    "supportive": "支援的な",
    "swollen": "腫れた",
    "systematic": "系統的な",
    "tasteless": "味のない",
    "technological": "技術的な",
    "thorough": "徹底的な",
    "threatening": "脅威的な",
    "tiring": "疲れさせる",
    "total": "合計の",
    "tragic": "悲劇的な",
    "trustworthy": "信頼できる",
    "unbelievable": "信じられない",
    "unemployed": "失業した",
    "unfriendly": "不親切な",
    "upper": "上の",
    "vague": "漠然とした",
    "vain": "無駄な",
    "vegetarian": "菜食主義の",
    "virtual": "仮想の",
    "visual": "視覚的な",
    "wasteful": "無駄遣いの",
    "worthy": "価値のある",
    # 副詞
    "aboard": "船に乗って",
    "absolutely": "絶対に",
    "accidentally": "偶然に",
    "accurately": "正確に",
    "afterward": "その後",
    "afterwards": "その後",
    "aloud": "声に出して",
    "altogether": "完全に",
    "annually": "毎年",
    "anxiously": "心配して",
    "approximately": "おおよそ",
    "aside": "わきに",
    "barely": "かろうじて",
    "beautifully": "美しく",
    "boldly": "大胆に",
    "bravely": "勇敢に",
    "briefly": "簡潔に",
    "brightly": "明るく",
    "carelessly": "不注意に",
    "closely": "密接に",
    "commonly": "一般的に",
    "completely": "完全に",
    "consequently": "その結果",
    "constantly": "常に",
    "continually": "絶え間なく",
    "continuously": "続けて",
    "curiously": "好奇心を持って",
    "currently": "現在",
    "dangerously": "危険なほど",
    "definitely": "確かに",
    "desperately": "必死に",
    "differently": "異なって",
    "directly": "直接に",
    "diligently": "勤勉に",
    "dramatically": "劇的に",
    "effectively": "効果的に",
    "efficiently": "効率的に",
    "enormously": "非常に",
    "entirely": "完全に",
    "essentially": "本質的に",
    "eventually": "最終的に",
    "evidently": "明らかに",
    "exactly": "正確に",
    "exclusively": "もっぱら",
    "extensively": "広範に",
    "extremely": "非常に",
    "fairly": "かなり",
    "frequently": "頻繁に",
    "gently": "優しく",
    "gradually": "徐々に",
    "greatly": "大いに",
    "hardly": "ほとんど〜ない",
    "heavily": "重く",
    "honestly": "正直に",
    "immediately": "すぐに",
    "increasingly": "ますます",
    "independently": "独立して",
    "instantly": "即座に",
    "intensely": "激しく",
    "largely": "主に",
    "lately": "最近",
    "loosely": "緩く",
    "mainly": "主に",
    "merely": "単に",
    "mostly": "主に",
    "naturally": "自然に",
    "nearly": "ほぼ",
    "necessarily": "必ず",
    "normally": "普通に",
    "obviously": "明らかに",
    "officially": "公式に",
    "originally": "元々",
    "particularly": "特に",
    "perfectly": "完全に",
    "permanently": "永続的に",
    "personally": "個人的に",
    "physically": "身体的に",
    "possibly": "おそらく",
    "practically": "実際には",
    "previously": "以前に",
    "primarily": "主に",
    "probably": "おそらく",
    "properly": "適切に",
    "quickly": "素早く",
    "quietly": "静かに",
    "rapidly": "急速に",
    "rarely": "めったに〜ない",
    "rather": "かなり",
    "reasonably": "合理的に",
    "recently": "最近",
    "regularly": "定期的に",
    "relatively": "比較的",
    "remarkably": "著しく",
    "repeatedly": "繰り返して",
    "sadly": "悲しいことに",
    "seriously": "真剣に",
    "significantly": "著しく",
    "simply": "単純に",
    "slowly": "ゆっくり",
    "slightly": "わずかに",
    "smoothly": "滑らかに",
    "specifically": "具体的に",
    "steadily": "着実に",
    "strongly": "強く",
    "successfully": "うまく",
    "suddenly": "突然",
    "technically": "技術的に",
    "typically": "典型的に",
    "unfortunately": "残念ながら",
    "usually": "通常",
    "widely": "広く",
    # 名詞
    "examination": "試験",
    "laboratory": "実験室",
    "luggage": "荷物",
    "lodge": "小屋",
    "isle": "島",
    "backpacking": "バックパック旅行",
    "brainstorming": "ブレインストーミング",
    "examination": "試験",
    "harness": "ハーネス",
    "hatch": "ハッチ",
    "haunt": "幽霊が出る場所",
    "hop": "ホップ",
    "daze": "茫然",
}

# ── CEFR-J B2 から前2級に適した語（易しめのB2）────────────────────

TRANSLATIONS_B2: dict[str, str] = {
    # 動詞
    "abolish": "廃止する",
    "accumulate": "蓄積する",
    "adore": "崇拝する",
    "alert": "警告する",
    "alter": "変える",
    "amaze": "驚かせる",
    "amuse": "楽しませる",
    "anticipate": "予期する",
    "arouse": "呼び起こす",
    "assemble": "組み立てる",
    "assert": "主張する",
    "assess": "評価する",
    "assure": "保証する",
    "await": "待つ",
    "bully": "いじめる",
    "cease": "止まる",
    "certify": "証明する",
    "cheat": "ずるをする",
    "chew": "噛む",
    "clap": "拍手する",
    "coincide": "一致する",
    "commute": "通勤する",
    "compile": "まとめる",
    "conceal": "隠す",
    "conceive": "思いつく",
    "condemn": "非難する",
    "confess": "告白する",
    "console": "慰める",
    "decline": "断る",
    "encounter": "出会う",
    "enforce": "施行する",
    "enhance": "高める",
    "innovate": "革新する",
    "integrate": "統合する",
    "justify": "正当化する",
    "maximize": "最大化する",
    "minimize": "最小化する",
    "predict": "予測する",
    "regulate": "規制する",
    "reinforce": "強化する",
    "simulate": "シミュレートする",
    "specialize": "専門にする",
    "stabilize": "安定させる",
    "standardize": "標準化する",
    "stimulate": "刺激する",
    "substitute": "代替する",
    "supervise": "監督する",
    "sustain": "維持する",
    "visualize": "視覚化する",
    "withdraw": "引き出す",
    # 名詞
    "penalty": "罰則",
    "percentage": "割合",
    "pedestrian": "歩行者",
    "peak": "頂点",
    "pension": "年金",
    "payment": "支払い",
    "phenomenon": "現象",
    "philosopher": "哲学者",
    "pioneer": "先駆者",
    "pollution": "汚染",
    "portrait": "肖像画",
    "poverty": "貧困",
    "prejudice": "偏見",
    "presentation": "発表",
    "preservation": "保存",
    "privilege": "特権",
    "procedure": "手順",
    "profession": "職業",
    "proposal": "提案",
    "psychology": "心理学",
    "publicity": "広告",
    "punishment": "罰",
    "qualification": "資格",
    "questionnaire": "アンケート",
    "quotation": "引用",
    "radiation": "放射線",
    "recession": "不況",
    "referendum": "国民投票",
    "refugee": "難民",
    "renewable": "再生可能",
    "reputation": "評判",
    "reservation": "予約",
    "restriction": "制限",
    "retail": "小売り",
    "revenue": "収入",
    "revolution": "革命",
    "sanitation": "衛生",
    "satisfaction": "満足",
    "scholarship": "奨学金",
    "seminar": "セミナー",
    "significance": "重要性",
    "statistic": "統計",
    "stereotype": "固定観念",
    "subsidy": "補助金",
    "supervisor": "上司",
    "survey": "調査",
    "sustainability": "持続可能性",
    "symptom": "症状",
    "taxation": "課税",
    "technique": "技術",
    "terrorism": "テロ",
    "transaction": "取引",
    "transformation": "変革",
    "transportation": "輸送",
    "unemployment": "失業",
    "vaccination": "ワクチン接種",
    "vegetation": "植物",
    "violation": "違反",
    "volunteer": "ボランティア",
    "vulnerability": "脆弱性",
    "workforce": "労働力",
    # 形容詞
    "abstract": "抽象的な",
    "adequate": "十分な",
    "ambitious": "野心的な",
    "appropriate": "適切な",
    "capable": "有能な",
    "cognitive": "認知の",
    "comprehensive": "包括的な",
    "consistent": "一貫した",
    "constructive": "建設的な",
    "convenient": "便利な",
    "cooperative": "協力的な",
    "creative": "創造的な",
    "crucial": "重要な",
    "democratic": "民主的な",
    "dominant": "支配的な",
    "dynamic": "活動的な",
    "efficient": "効率的な",
    "elderly": "高齢の",
    "eligible": "適格な",
    "essential": "不可欠な",
    "evident": "明らかな",
    "excessive": "過度な",
    "flexible": "柔軟な",
    "fundamental": "基本的な",
    "genuine": "本物の",
    "harmful": "有害な",
    "helpful": "役に立つ",
    "identical": "同一の",
    "illegal": "違法な",
    "influential": "影響力のある",
    "innovative": "革新的な",
    "intellectual": "知的な",
    "logical": "論理的な",
    "mandatory": "義務的な",
    "meaningful": "意味のある",
    "neutral": "中立の",
    "nutritious": "栄養のある",
    "objective": "客観的な",
    "optional": "任意の",
    "passionate": "情熱的な",
    "potential": "可能性のある",
    "practical": "実用的な",
    "productive": "生産的な",
    "rational": "合理的な",
    "realistic": "現実的な",
    "relevant": "関連のある",
    "renewable": "再生可能な",
    "resistant": "抵抗力のある",
    "responsible": "責任のある",
    "sensitive": "敏感な",
    "sophisticated": "洗練された",
    "statistical": "統計的な",
    "subjective": "主観的な",
    "substantial": "かなりの",
    "sustainable": "持続可能な",
    "symbolic": "象徴的な",
    "transparent": "透明な",
    "urgent": "緊急の",
    "voluntary": "自発的な",
    "vulnerable": "傷つきやすい",
}

# ── 独自 CANDIDATES 動詞 ───────────────────────────────────────────
# (en, ja, theme)
CANDIDATES_VERBS: list[tuple[str, str, str]] = [
    ("add", "加える", "action"),
    ("adjust", "調整する", "action"),
    ("admire", "称賛する", "mind"),
    ("advise", "助言する", "action"),
    ("agree", "同意する", "mind"),
    ("allow", "許可する", "action"),
    ("analyze", "分析する", "action"),
    ("apologize", "謝る", "action"),
    ("apply", "申し込む", "action"),
    ("appreciate", "感謝する", "mind"),
    ("argue", "議論する", "action"),
    ("attempt", "試みる", "action"),
    ("avoid", "避ける", "action"),
    ("beg", "懇願する", "action"),
    ("believe", "信じる", "mind"),
    ("belong", "属する", "general"),
    ("boost", "高める", "action"),
    ("break", "壊す", "action"),
    ("bring", "持ってくる", "action"),
    ("capture", "捕らえる", "action"),
    ("cause", "引き起こす", "action"),
    ("change", "変える", "action"),
    ("charge", "請求する", "action"),
    ("check", "確認する", "action"),
    ("choose", "選ぶ", "action"),
    ("claim", "主張する", "action"),
    ("clarify", "明確にする", "action"),
    ("collaborate", "協力する", "people"),
    ("communicate", "伝える", "people"),
    ("compare", "比較する", "action"),
    ("compete", "競争する", "people"),
    ("complain", "不満を言う", "mind"),
    ("confirm", "確認する", "action"),
    ("consider", "考慮する", "mind"),
    ("contact", "連絡する", "people"),
    ("control", "制御する", "action"),
    ("convert", "変換する", "action"),
    ("cooperate", "協力する", "people"),
    ("copy", "コピーする", "action"),
    ("correct", "訂正する", "action"),
    ("cost", "費用がかかる", "general"),
    ("count", "数える", "action"),
    ("create", "作る", "action"),
    ("criticize", "批判する", "action"),
    ("damage", "損傷する", "action"),
    ("debate", "討論する", "action"),
    ("defeat", "打ち負かす", "action"),
    ("delay", "遅らせる", "action"),
    ("demand", "要求する", "action"),
    ("depend", "依存する", "general"),
    ("destroy", "破壊する", "action"),
    ("develop", "発展する", "action"),
    ("discuss", "話し合う", "people"),
    ("display", "表示する", "action"),
    ("divide", "分ける", "action"),
    ("donate", "寄付する", "people"),
    ("doubt", "疑う", "mind"),
    ("draw", "描く", "action"),
    ("drop", "落とす", "action"),
    ("emphasize", "強調する", "action"),
    ("encourage", "励ます", "mind"),
    ("enter", "入る", "action"),
    ("establish", "設立する", "action"),
    ("evaluate", "評価する", "action"),
    ("exchange", "交換する", "action"),
    ("expect", "期待する", "mind"),
    ("express", "表現する", "action"),
    ("face", "直面する", "action"),
    ("focus", "集中する", "mind"),
    ("force", "強制する", "action"),
    ("function", "機能する", "general"),
    ("gain", "得る", "action"),
    ("gather", "集まる", "action"),
    ("go", "行く", "action"),
    ("greet", "挨拶する", "people"),
    ("guide", "案内する", "action"),
    ("handle", "扱う", "action"),
    ("harm", "傷つける", "action"),
    ("hate", "嫌いである", "mind"),
    ("hide", "隠れる", "action"),
    ("identify", "特定する", "action"),
    ("illustrate", "説明する", "action"),
    ("imagine", "想像する", "mind"),
    ("include", "含む", "general"),
    ("indicate", "示す", "action"),
    ("influence", "影響を与える", "action"),
    ("install", "インストールする", "action"),
    ("investigate", "調査する", "action"),
    ("join", "参加する", "people"),
    ("judge", "判断する", "mind"),
    ("keep", "保つ", "action"),
    ("lead", "導く", "action"),
    ("limit", "制限する", "action"),
    ("manage", "管理する", "action"),
    ("measure", "測る", "action"),
    ("memorize", "暗記する", "action"),
    ("mix", "混ぜる", "action"),
    ("monitor", "監視する", "action"),
    ("move", "動く", "action"),
    ("negotiate", "交渉する", "people"),
    ("operate", "操作する", "action"),
    ("order", "命令する", "action"),
    ("organize", "組織する", "action"),
    ("pass", "通過する", "action"),
    ("pay", "払う", "action"),
    ("prefer", "好む", "mind"),
    ("present", "提示する", "action"),
    ("prevent", "防ぐ", "action"),
    ("process", "処理する", "action"),
    ("provide", "提供する", "action"),
    ("publish", "出版する", "action"),
    ("reach", "達する", "action"),
    ("recognize", "認識する", "mind"),
    ("recycle", "リサイクルする", "nature"),
    ("refuse", "断る", "action"),
    ("remain", "残る", "action"),
    ("represent", "代表する", "people"),
    ("research", "研究する", "action"),
    ("reveal", "明らかにする", "action"),
    ("review", "見直す", "action"),
    ("run", "走る", "action"),
    ("save", "救う", "action"),
    ("select", "選ぶ", "action"),
    ("send", "送る", "action"),
    ("share", "共有する", "people"),
    ("solve", "解決する", "action"),
    ("start", "始める", "action"),
    ("stop", "止める", "action"),
    ("store", "保存する", "action"),
    ("submit", "提出する", "action"),
    ("summarize", "まとめる", "action"),
    ("survive", "生き残る", "action"),
    ("test", "試す", "action"),
    ("trust", "信頼する", "mind"),
    ("utilize", "活用する", "action"),
    ("visit", "訪れる", "place"),
    ("volunteer", "ボランティアをする", "people"),
    ("watch", "見る", "action"),
    ("work", "働く", "action"),
    ("write", "書く", "action"),
    # 追加
    ("accelerate", "加速する", "action"),
    ("accumulate", "蓄積する", "action"),
    ("activate", "活性化する", "action"),
    ("allocate", "割り当てる", "action"),
    ("authorize", "許可する", "action"),
    ("browse", "閲覧する", "action"),
    ("challenge", "挑戦する", "action"),
    ("compensate", "補償する", "action"),
    ("concentrate", "集中する", "mind"),
    ("consume", "消費する", "action"),
    ("contrast", "対比する", "action"),
    ("coordinate", "調整する", "action"),
    ("customize", "カスタマイズする", "action"),
    ("decide", "決める", "mind"),
    ("decrease", "減少する", "action"),
    ("donate", "寄付する", "people"),
    ("download", "ダウンロードする", "action"),
    ("earn", "稼ぐ", "action"),
    ("experience", "経験する", "action"),
    ("explore", "探索する", "place"),
    ("export", "輸出する", "action"),
    ("fail", "失敗する", "action"),
    ("finance", "資金を提供する", "people"),
    ("finish", "終わらせる", "action"),
    ("follow", "従う", "action"),
    ("forecast", "予測する", "action"),
    ("fund", "資金提供する", "people"),
    ("help", "助ける", "people"),
    ("implement", "実施する", "action"),
    ("import", "輸入する", "action"),
    ("increase", "増やす", "action"),
    ("introduce", "紹介する", "people"),
    ("know", "知っている", "mind"),
    ("learn", "学ぶ", "action"),
    ("link", "リンクする", "action"),
    ("lose", "失う", "action"),
    ("lower", "下げる", "action"),
    ("mention", "述べる", "action"),
    ("miss", "見逃す", "action"),
    ("motivate", "動機づける", "mind"),
    ("need", "必要とする", "general"),
    ("offer", "提供する", "action"),
    ("open", "開ける", "action"),
    ("overcome", "克服する", "action"),
    ("perform", "行う", "action"),
    ("plan", "計画する", "action"),
    ("prepare", "準備する", "action"),
    ("produce", "生産する", "action"),
    ("promise", "約束する", "action"),
    ("protect", "保護する", "action"),
    ("push", "押す", "action"),
    ("raise", "上げる", "action"),
    ("realize", "気づく", "mind"),
    ("receive", "受け取る", "action"),
    ("recommend", "勧める", "action"),
    ("relax", "リラックスする", "mind"),
    ("remember", "覚えている", "mind"),
    ("repair", "修理する", "action"),
    ("report", "報告する", "action"),
    ("spend", "費やす", "action"),
    ("spread", "広める", "action"),
    ("steal", "盗む", "action"),
    ("struggle", "苦しむ", "action"),
    ("succeed", "成功する", "action"),
    ("support", "支援する", "people"),
    ("throw", "投げる", "action"),
    ("transfer", "転送する", "action"),
    ("travel", "旅行する", "place"),
    ("understand", "理解する", "mind"),
    ("update", "更新する", "action"),
    ("use", "使う", "action"),
    ("wake", "起きる", "action"),
    ("warn", "警告する", "action"),
    ("wonder", "不思議に思う", "mind"),
    ("wrap", "包む", "action"),
    # ── 追加動詞（より高度な前2級レベル）────────────────────────
    ("achieve", "達成する", "action"),
    ("approve", "承認する", "action"),
    ("belong", "属する", "general"),
    ("broadcast", "放送する", "action"),
    ("calculate", "計算する", "action"),
    ("cancel", "キャンセルする", "action"),
    ("cause", "引き起こす", "action"),
    ("collect", "集める", "action"),
    ("complete", "完了する", "action"),
    ("connect", "接続する", "action"),
    ("consider", "考慮する", "mind"),
    ("continue", "続ける", "action"),
    ("convince", "説得する", "action"),
    ("cooperate", "協力する", "people"),
    ("deliver", "届ける", "action"),
    ("describe", "説明する", "action"),
    ("design", "デザインする", "action"),
    ("determine", "決定する", "action"),
    ("discover", "発見する", "action"),
    ("distribute", "配布する", "action"),
    ("divide", "分ける", "action"),
    ("educate", "教育する", "people"),
    ("eliminate", "排除する", "action"),
    ("enable", "可能にする", "action"),
    ("ensure", "確保する", "action"),
    ("establish", "設立する", "action"),
    ("estimate", "見積もる", "action"),
    ("examine", "調べる", "action"),
    ("expand", "拡大する", "action"),
    ("extend", "延長する", "action"),
    ("fix", "修理する", "action"),
    ("generate", "生み出す", "action"),
    ("govern", "統治する", "people"),
    ("guarantee", "保証する", "action"),
    ("highlight", "強調する", "action"),
    ("improve", "改善する", "action"),
    ("include", "含む", "general"),
    ("increase", "増やす", "action"),
    ("indicate", "示す", "action"),
    ("influence", "影響する", "action"),
    ("inform", "知らせる", "people"),
    ("introduce", "紹介する", "people"),
    ("launch", "発売する", "action"),
    ("maintain", "維持する", "action"),
    ("modify", "修正する", "action"),
    ("motivate", "やる気にさせる", "mind"),
    ("negotiate", "交渉する", "people"),
    ("observe", "観察する", "action"),
    ("obtain", "得る", "action"),
    ("organize", "整理する", "action"),
    ("overcome", "克服する", "action"),
    ("participate", "参加する", "people"),
    ("perform", "行う", "action"),
    ("permit", "許可する", "action"),
    ("persuade", "説得する", "action"),
    ("plan", "計画する", "action"),
    ("prepare", "準備する", "action"),
    ("produce", "生産する", "action"),
    ("promote", "促進する", "action"),
    ("propose", "提案する", "action"),
    ("prove", "証明する", "action"),
    ("provide", "提供する", "action"),
    ("reduce", "減らす", "action"),
    ("reflect", "反映する", "action"),
    ("relate", "関連する", "general"),
    ("release", "解放する", "action"),
    ("rely", "頼る", "action"),
    ("remove", "取り除く", "action"),
    ("require", "必要とする", "general"),
    ("restore", "回復する", "action"),
    ("restrict", "制限する", "action"),
    ("seek", "求める", "action"),
    ("settle", "解決する", "action"),
    ("simplify", "単純化する", "action"),
    ("strengthen", "強化する", "action"),
    ("suggest", "提案する", "action"),
    ("supply", "供給する", "action"),
    ("survey", "調査する", "action"),
    ("target", "目標にする", "action"),
    ("track", "追跡する", "action"),
    ("transform", "変える", "action"),
    ("translate", "翻訳する", "action"),
    ("treat", "扱う", "action"),
    ("trigger", "引き起こす", "action"),
    ("vary", "変化する", "general"),
]

# ── 独自 CANDIDATES 名詞 ─────────────────────────────────────────
# (en, ja, theme)
CANDIDATES_NOUNS: list[tuple[str, str, str]] = [
    ("ability", "能力", "general"),
    ("account", "口座", "general"),
    ("advantage", "利点", "general"),
    ("agreement", "合意", "people"),
    ("analysis", "分析", "general"),
    ("application", "応募", "general"),
    ("argument", "議論", "people"),
    ("aspect", "側面", "general"),
    ("attention", "注意", "mind"),
    ("attitude", "態度", "mind"),
    ("background", "背景", "general"),
    ("behavior", "行動", "people"),
    ("budget", "予算", "general"),
    ("career", "キャリア", "people"),
    ("category", "カテゴリー", "general"),
    ("challenge", "挑戦", "general"),
    ("characteristic", "特徴", "general"),
    ("choice", "選択", "general"),
    ("circumstance", "状況", "general"),
    ("comparison", "比較", "general"),
    ("concept", "概念", "general"),
    ("condition", "条件", "general"),
    ("conference", "会議", "people"),
    ("consequence", "結果", "general"),
    ("context", "文脈", "general"),
    ("data", "データ", "general"),
    ("definition", "定義", "general"),
    ("development", "発展", "general"),
    ("difference", "違い", "general"),
    ("direction", "方向", "place"),
    ("discussion", "議論", "people"),
    ("document", "書類", "general"),
    ("economy", "経済", "people"),
    ("effect", "効果", "general"),
    ("effort", "努力", "action"),
    ("element", "要素", "general"),
    ("equipment", "設備", "general"),
    ("evaluation", "評価", "general"),
    ("evidence", "証拠", "general"),
    ("example", "例", "general"),
    ("explanation", "説明", "general"),
    ("feature", "特徴", "general"),
    ("figure", "数字", "general"),
    ("goal", "目標", "general"),
    ("impact", "影響", "general"),
    ("improvement", "改善", "general"),
    ("income", "収入", "people"),
    ("information", "情報", "general"),
    ("innovation", "革新", "general"),
    ("institution", "機関", "people"),
    ("investment", "投資", "people"),
    ("issue", "問題", "general"),
    ("knowledge", "知識", "general"),
    ("leadership", "リーダーシップ", "people"),
    ("material", "材料", "general"),
    ("method", "方法", "general"),
    ("model", "モデル", "general"),
    ("movement", "運動", "action"),
    ("network", "ネットワーク", "general"),
    ("organization", "組織", "people"),
    ("outcome", "結果", "general"),
    ("pattern", "パターン", "general"),
    ("performance", "パフォーマンス", "people"),
    ("period", "期間", "general"),
    ("perspective", "視点", "mind"),
    ("population", "人口", "people"),
    ("position", "立場", "general"),
    ("potential", "可能性", "general"),
    ("practice", "練習", "action"),
    ("principle", "原則", "general"),
    ("process", "過程", "general"),
    ("project", "プロジェクト", "people"),
    ("quality", "品質", "general"),
    ("quantity", "量", "general"),
    ("reaction", "反応", "general"),
    ("requirement", "要件", "general"),
    ("resource", "資源", "nature"),
    ("role", "役割", "people"),
    ("rule", "ルール", "general"),
    ("scale", "規模", "general"),
    ("schedule", "スケジュール", "general"),
    ("situation", "状況", "general"),
    ("skill", "スキル", "general"),
    ("solution", "解決策", "general"),
    ("source", "出所", "general"),
    ("stage", "段階", "general"),
    ("standard", "基準", "general"),
    ("strategy", "戦略", "general"),
    ("structure", "構造", "general"),
    ("subject", "科目", "people"),
    ("success", "成功", "general"),
    ("system", "システム", "general"),
    ("technology", "技術", "general"),
    ("term", "用語", "general"),
    ("theory", "理論", "general"),
    ("tool", "ツール", "general"),
    ("trend", "傾向", "general"),
    ("value", "価値", "general"),
    ("variety", "多様性", "general"),
    ("version", "バージョン", "general"),
    ("view", "見解", "mind"),
    ("vision", "ビジョン", "mind"),
    ("wealth", "富", "people"),
    ("welfare", "福祉", "people"),
    # 追加名詞
    ("address", "住所", "place"),
    ("administration", "管理", "people"),
    ("benefit", "利益", "general"),
    ("competition", "競争", "people"),
    ("connection", "つながり", "people"),
    ("conservation", "保護", "nature"),
    ("contribution", "貢献", "people"),
    ("cooperation", "協力", "people"),
    ("copyright", "著作権", "general"),
    ("creativity", "創造性", "mind"),
    ("criticism", "批判", "mind"),
    ("curiosity", "好奇心", "mind"),
    ("deadline", "締め切り", "general"),
    ("democracy", "民主主義", "people"),
    ("destination", "目的地", "place"),
    ("diversity", "多様性", "general"),
    ("efficiency", "効率", "general"),
    ("election", "選挙", "people"),
    ("equality", "平等", "people"),
    ("event", "出来事", "general"),
    ("examination", "試験", "people"),
    ("exhibition", "展覧会", "place"),
    ("expectation", "期待", "mind"),
    ("experiment", "実験", "general"),
    ("expert", "専門家", "people"),
    ("facility", "施設", "place"),
    ("factor", "要因", "general"),
    ("feedback", "フィードバック", "general"),
    ("freedom", "自由", "general"),
    ("function", "機能", "general"),
    ("generation", "世代", "people"),
    ("government", "政府", "people"),
    ("guideline", "指針", "general"),
    ("identity", "アイデンティティ", "people"),
    ("imagination", "想像力", "mind"),
    ("independence", "独立", "general"),
    ("industry", "産業", "people"),
    ("influence", "影響力", "general"),
    ("infrastructure", "インフラ", "place"),
    ("initiative", "取り組み", "general"),
    ("inspiration", "インスピレーション", "mind"),
    ("interaction", "交流", "people"),
    ("laboratory", "実験室", "place"),
    ("landscape", "景色", "nature"),
    ("legislation", "法律", "people"),
    ("lifestyle", "生活様式", "daily"),
    ("literature", "文学", "general"),
    ("location", "場所", "place"),
    ("management", "経営", "people"),
    ("media", "メディア", "general"),
    ("mission", "使命", "general"),
    ("motivation", "動機", "mind"),
    ("observation", "観察", "general"),
    ("permission", "許可", "general"),
    ("phenomenon", "現象", "general"),
    ("priority", "優先事項", "general"),
    ("productivity", "生産性", "general"),
    ("profession", "職業", "people"),
    ("profit", "利益", "people"),
    ("promotion", "昇進", "people"),
    ("publication", "出版物", "general"),
    ("regulation", "規制", "general"),
    ("relationship", "関係", "people"),
    ("reputation", "評判", "people"),
    ("research", "研究", "general"),
    ("resolution", "解決", "general"),
    ("responsibility", "責任", "people"),
    ("revolution", "革命", "people"),
    ("routine", "ルーティン", "daily"),
    ("selection", "選択", "general"),
    ("sensitivity", "敏感さ", "mind"),
    ("significance", "重要性", "general"),
    ("sustainability", "持続可能性", "nature"),
    ("symbol", "象徴", "general"),
    ("tradition", "伝統", "people"),
    ("transformation", "変革", "general"),
    ("transportation", "輸送", "place"),
    ("understanding", "理解", "mind"),
]

# ── CEFR-J → アプリ theme ─────────────────────────────────────────

CORE_TO_THEME = {
    "Animals": "nature",
    "Food and drink": "nature",
    "Plants and environment": "nature",
    "Weather and climate": "nature",
    "Colour and shape": "nature",
    "Natural features": "nature",
    "Body and health": "daily",
    "The home": "daily",
    "Time": "daily",
    "Physical description": "daily",
    "Clothes": "daily",
    "Education": "people",
    "Work and Jobs": "people",
    "Family and friends": "people",
    "Society": "people",
    "Sport and leisure": "people",
    "Entertainment": "people",
    "Travel and transport": "place",
    "Places and buildings": "place",
    "Geography and environment": "place",
    "Feelings and opinions": "mind",
    "Personality and character": "mind",
    "Thoughts and thinking": "mind",
    "Language and communication": "general",
    "Numbers and quantity": "general",
    "Technology": "general",
}

EXCLUDE = [
    re.compile(r"^[a-z]\.$"),
    re.compile(r"[/\.\-]"),
    re.compile(r"\s"),
    re.compile(r"'"),
]
FUNCTION_WORDS = {
    "a", "an", "the", "is", "are", "was", "were", "be", "been", "being",
    "have", "has", "had", "do", "does", "did", "will", "would", "could",
    "should", "may", "might", "shall", "can", "must", "not", "very",
    "all", "both", "each", "any", "some", "no", "this", "that", "these",
    "those", "i", "you", "he", "she", "it", "we", "they", "who", "which",
    "what", "when", "where", "why", "how", "and", "or", "but", "so", "if",
    "then", "my", "your", "his", "her", "its", "our", "their",
    "me", "him", "us", "them",
}


def is_excluded(word: str) -> bool:
    if word.lower() in FUNCTION_WORDS:
        return True
    return any(p.search(word) for p in EXCLUDE)


def infer_theme(core_inv: str, pos: str) -> str:
    if pos == "verb":
        return "action"
    if pos == "adjective" and "Feeling" in core_inv:
        return "mind"
    return CORE_TO_THEME.get(core_inv, "general")


CEFR_POS_TO_APP = {
    "noun": "noun",
    "verb": "verb",
    "adjective": "adjective",
    "adverb": "adverb",
    "preposition": "preposition",
    "conjunction": "conjunction",
    "determiner": "conjunction",
    "pronoun": "noun",
    "number": "noun",
    "interjection": "general",
}


def main() -> None:
    out_path = sys.argv[1] if len(sys.argv) > 1 else "tools/draft_eiken_pre2_additional.csv"

    with open("assets/quiz/words.csv", newline="", encoding="utf-8") as f:
        rows = list(csv.DictReader(f))

    upper_words = {r["en"].lower() for r in rows if r["level"] in ("eiken5", "eiken4", "eiken3")}
    pre2_existing = [r for r in rows if r["level"] == "eiken_pre2"]
    pre2_kept = [r for r in pre2_existing if r["en"].lower() not in upper_words]
    all_existing = {r["en"].lower() for r in rows}

    target = 1100
    need = target - len(pre2_kept)
    print(f"重複削除後 eiken_pre2: {len(pre2_kept)}語")
    print(f"追加必要数: {need}語")

    with open("tools/data/cefrj.csv", newline="", encoding="utf-8") as f:
        cefrj = list(csv.DictReader(f))

    # CEFR-J B1 残存から追加
    b1_additions: list[dict] = []
    seen: set[str] = set()
    for row in cefrj:
        if row.get("CEFR", "").strip() != "B1":
            continue
        word = row.get("headword", "").strip()
        key = word.lower()
        if not word or key in all_existing or key in seen:
            continue
        if is_excluded(word):
            continue
        if key not in TRANSLATIONS_B1:
            continue
        seen.add(key)
        cefr_pos = row.get("pos", "").strip().lower()
        app_pos = CEFR_POS_TO_APP.get(cefr_pos, "noun")
        if app_pos in ("preposition", "conjunction", "general"):
            continue
        core_inv = row.get("CoreInventory", "").strip()
        b1_additions.append({
            "en": word,
            "ja": TRANSLATIONS_B1[key],
            "pos": app_pos,
            "theme": infer_theme(core_inv, app_pos),
            "level": "eiken_pre2",
        })

    # CEFR-J B2 から前2級適語も追加
    for row in cefrj:
        if row.get("CEFR", "").strip() != "B2":
            continue
        word = row.get("headword", "").strip()
        key = word.lower()
        if not word or key in all_existing or key in seen:
            continue
        if is_excluded(word):
            continue
        if key not in TRANSLATIONS_B2:
            continue
        seen.add(key)
        cefr_pos = row.get("pos", "").strip().lower()
        app_pos = CEFR_POS_TO_APP.get(cefr_pos, "noun")
        if app_pos in ("preposition", "conjunction", "general"):
            continue
        core_inv = row.get("CoreInventory", "").strip()
        b1_additions.append({
            "en": word,
            "ja": TRANSLATIONS_B2[key],
            "pos": app_pos,
            "theme": infer_theme(core_inv, app_pos),
            "level": "eiken_pre2",
        })

    pos_b1 = Counter(r["pos"] for r in b1_additions)
    print(f"B1+B2 から取得: {len(b1_additions)}語 {dict(sorted(pos_b1.items()))}")

    # CANDIDATES 動詞
    cand_verbs: list[dict] = []
    for en, ja, theme in CANDIDATES_VERBS:
        key = en.lower()
        if key in all_existing or key in seen:
            continue
        seen.add(key)
        cand_verbs.append({"en": en, "ja": ja, "pos": "verb", "theme": theme, "level": "eiken_pre2"})

    # CANDIDATES 名詞
    cand_nouns: list[dict] = []
    for en, ja, theme in CANDIDATES_NOUNS:
        key = en.lower()
        if key in all_existing or key in seen:
            continue
        seen.add(key)
        cand_nouns.append({"en": en, "ja": ja, "pos": "noun", "theme": theme, "level": "eiken_pre2"})

    print(f"CANDIDATES 動詞: {len(cand_verbs)}語  名詞: {len(cand_nouns)}語")

    # 結合して need 語選出（B1 → 動詞 → 名詞 の順で優先）
    additions = (b1_additions + cand_verbs + cand_nouns)[:need]

    pos_all = Counter(r["pos"] for r in additions)
    print(f"合計追加: {len(additions)}語 {dict(sorted(pos_all.items()))}")

    with open(out_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(
            f,
            fieldnames=["id", "en", "ja", "pos", "theme", "level", "notes"],
        )
        writer.writeheader()
        for i, r in enumerate(additions, start=1):
            writer.writerow({
                "id": i,
                "en": r["en"],
                "ja": r["ja"],
                "pos": r["pos"],
                "theme": r["theme"],
                "level": "eiken_pre2",
                "notes": "",
            })

    print(f"\n✅ 下書き生成: {len(additions)}語 → {out_path}")
    print(f"   eiken_pre2 既存(重複削除後): {len(pre2_kept)}語")
    print(f"   追加後の合計: {len(pre2_kept) + len(additions)}語")


if __name__ == "__main__":
    main()
