#!/usr/bin/env python3
"""
英検2級 追加単語生成スクリプト

- 上位レベルとの重複9語を削除
- CEFR-J B2 動詞(289)・形容詞(~300)・副詞(~126) で拡張
- 目標: 1,500語（累計 ~5,400語）

使い方:
    python3 tools/generate_eiken2_additional.py
"""

import csv
import re
import sys
from collections import Counter

# ── 日本語訳辞書 ─────────────────────────────────────────────────

TRANSLATIONS: dict[str, str] = {
    # ── 動詞 (289) ──────────────────────────────────────────────
    "adorn": "飾る",
    "alternate": "交互にする",
    "amplify": "増幅する",
    "animate": "生き生きとさせる",
    "articulate": "はっきり話す",
    "astonish": "驚かせる",
    "bankrupt": "破産させる",
    "beautify": "美化する",
    "bellow": "怒鳴る",
    "bestow": "授ける",
    "bewilder": "当惑させる",
    "bid": "入札する",
    "bind": "縛る",
    "blur": "ぼかす",
    "bottle": "ビンに詰める",
    "burgle": "押し入る",
    "bustle": "忙しく動く",
    "clog": "詰まらせる",
    "compute": "計算する",
    "concede": "認める",
    "confine": "閉じ込める",
    "confront": "対峙する",
    "contradict": "矛盾する",
    "decay": "腐る",
    "deduce": "推論する",
    "deem": "みなす",
    "defy": "反抗する",
    "demolish": "取り壊す",
    "descend": "降りる",
    "despise": "軽蔑する",
    "detach": "取り外す",
    "detect": "検出する",
    "devote": "捧げる",
    "dignify": "品格を与える",
    "dip": "浸す",
    "disapprove": "不承認とする",
    "disconnect": "切断する",
    "discredit": "信用を失わせる",
    "discriminate": "差別する",
    "disillusion": "幻滅させる",
    "dismiss": "却下する",
    "displace": "移動させる",
    "disqualify": "失格にする",
    "disrupt": "混乱させる",
    "distract": "気をそらす",
    "divert": "そらす",
    "dominate": "支配する",
    "downsize": "縮小する",
    "dread": "恐れる",
    "elect": "選出する",
    "employ": "雇用する",
    "endorse": "支持する",
    "engulf": "飲み込む",
    "entitle": "権利を与える",
    "equip": "装備する",
    "erupt": "噴火する",
    "evacuate": "避難する",
    "evolve": "進化する",
    "exalt": "称える",
    "exceed": "超える",
    "excel": "優れる",
    "exclaim": "叫ぶ",
    "exclude": "除外する",
    "execute": "実行する",
    "exhibit": "展示する",
    "explode": "爆発する",
    "exploit": "利用する",
    "facilitate": "促進する",
    "falter": "よろめく",
    "file": "申請する",
    "flap": "羽ばたく",
    "flee": "逃げる",
    "flip": "ひっくり返す",
    "foresee": "予見する",
    "found": "設立する",
    "freak": "動揺する",
    "glorify": "称える",
    "grieve": "悲しむ",
    "hail": "歓迎する",
    "hover": "浮かぶ",
    "humiliate": "屈辱を与える",
    "hush": "静かにさせる",
    "immerse": "没頭させる",
    "imply": "意味する",
    "impose": "課す",
    "imprison": "投獄する",
    "incur": "招く",
    "indulge": "ふける",
    "infect": "感染させる",
    "infer": "推論する",
    "inflate": "膨らませる",
    "infringe": "侵害する",
    "inhabit": "住む",
    "inherit": "相続する",
    "inspect": "検査する",
    "instruct": "指示する",
    "interfere": "干渉する",
    "interpret": "解釈する",
    "intrude": "侵入する",
    "invoke": "呼び起こす",
    "itch": "かゆくなる",
    "jam": "詰まる",
    "kneel": "ひざまずく",
    "lack": "欠如する",
    "legislate": "立法する",
    "lengthen": "長くする",
    "lick": "なめる",
    "lighten": "軽くする",
    "line": "並ぶ",
    "linger": "たたずむ",
    "list": "一覧にする",
    "load": "積む",
    "magnify": "拡大する",
    "manipulate": "操る",
    "merge": "合併する",
    "mistreat": "虐待する",
    "misunderstand": "誤解する",
    "mortify": "恥ずかしめる",
    "multiply": "増やす",
    "muse": "考え込む",
    "mystify": "謎めかせる",
    "navigate": "航行する",
    "nourish": "栄養を与える",
    "obey": "従う",
    "obsess": "とりつく",
    "offend": "傷つける",
    "originate": "生じる",
    "outdistance": "引き離す",
    "outdo": "上回る",
    "outgrow": "成長して合わなくなる",
    "outlive": "長生きする",
    "outshine": "勝る",
    "overbook": "予約オーバーにする",
    "overestimate": "過大評価する",
    "overhear": "聞こえてしまう",
    "overlook": "見落とす",
    "overshadow": "陰にする",
    "overstep": "踏み越える",
    "overtake": "追い越す",
    "overthrow": "打倒する",
    "overturn": "ひっくり返す",
    "panic": "パニックになる",
    "part": "別れる",
    "pave": "舗装する",
    "penetrate": "貫通する",
    "perceive": "知覚する",
    "permeate": "浸透する",
    "persist": "持続する",
    "personify": "擬人化する",
    "photograph": "写真を撮る",
    "plead": "懇願する",
    "pluck": "引き抜く",
    "ponder": "熟考する",
    "pop": "飛び出す",
    "postpone": "延期する",
    "precede": "先行する",
    "prescribe": "処方する",
    "prevail": "勝る",
    "prohibit": "禁止する",
    "prosecute": "起訴する",
    "prosper": "繁栄する",
    "quantify": "数値化する",
    "radiate": "放射する",
    "range": "及ぶ",
    "rate": "評価する",
    "reckon": "計算する",
    "recollect": "思い出す",
    "reconsider": "再考する",
    "recruit": "採用する",
    "redo": "やり直す",
    "refute": "反証する",
    "rejoin": "再加入する",
    "relieve": "和らげる",
    "repress": "抑圧する",
    "reprove": "叱る",
    "resign": "辞職する",
    "resume": "再開する",
    "retard": "遅らせる",
    "retrieve": "取り戻す",
    "reverse": "逆にする",
    "revive": "復活させる",
    "revolve": "回転する",
    "rhyme": "韻を踏む",
    "rip": "引き裂く",
    "roar": "轟音をたてる",
    "rock": "揺れる",
    "roll": "転がる",
    "row": "漕ぐ",
    "rub": "こする",
    "sack": "解雇する",
    "sail": "航海する",
    "saw": "のこぎりで切る",
    "scramble": "急いで動く",
    "screen": "選別する",
    "screw": "ねじ込む",
    "sense": "感じる",
    "sentence": "判決を下す",
    "separate": "分離する",
    "shatter": "粉砕する",
    "shock": "衝撃を与える",
    "shoplift": "万引きする",
    "shrug": "肩をすくめる",
    "signify": "意味する",
    "sketch": "スケッチする",
    "skim": "流し読みする",
    "skip": "飛ばす",
    "slam": "叩きつける",
    "slice": "薄切りにする",
    "slide": "滑る",
    "smash": "粉砕する",
    "snap": "パチンと折る",
    "sneak": "こそこそ動く",
    "sniff": "鼻をすする",
    "soar": "急上昇する",
    "sob": "泣きじゃくる",
    "span": "及ぶ",
    "specify": "指定する",
    "spin": "回転する",
    "spot": "見つける",
    "squeeze": "絞る",
    "stab": "刺す",
    "stammer": "口ごもる",
    "stamp": "スタンプを押す",
    "startle": "ぎょっとさせる",
    "starve": "飢える",
    "steer": "操縦する",
    "stink": "悪臭がする",
    "straighten": "まっすぐにする",
    "strangle": "絞め殺す",
    "stride": "大股で歩く",
    "strive": "努力する",
    "stuff": "詰め込む",
    "subside": "収まる",
    "subtract": "引き算する",
    "suck": "吸う",
    "sue": "訴える",
    "suppress": "抑制する",
    "surrender": "降参する",
    "suspend": "停止する",
    "sweep": "掃く",
    "tackle": "取り組む",
    "tap": "軽く叩く",
    "testify": "証言する",
    "threaten": "脅す",
    "tickle": "くすぐる",
    "tip": "傾ける",
    "toil": "苦労する",
    "tolerate": "我慢する",
    "torture": "拷問する",
    "trade": "取引する",
    "trail": "跡をつける",
    "transmit": "送信する",
    "transport": "輸送する",
    "tread": "踏む",
    "trick": "だます",
    "underestimate": "過小評価する",
    "undertake": "引き受ける",
    "unload": "荷降ろしする",
    "unlock": "解錠する",
    "untie": "ほどく",
    "upset": "動揺させる",
    "urge": "促す",
    "usher": "案内する",
    "utter": "口にする",
    "vanish": "消える",
    "vibrate": "振動する",
    "violate": "違反する",
    "weaken": "弱める",
    "wed": "結婚する",
    "whip": "むち打つ",
    "whisper": "ささやく",
    "whistle": "口笛を吹く",
    "widen": "広げる",
    "wipe": "ふく",
    "worsen": "悪化する",
    "wound": "傷つける",
    "yearn": "切望する",
    "yell": "叫ぶ",
    "yield": "産出する",
    # ── 形容詞 (~350) ──────────────────────────────────────────
    "abandoned": "見捨てられた",
    "absurd": "ばかげた",
    "achievable": "達成可能な",
    "actual": "実際の",
    "acute": "鋭い",
    "adaptable": "適応できる",
    "addicted": "中毒になった",
    "administrative": "行政の",
    "admirable": "称賛すべき",
    "adventurous": "冒険好きな",
    "adverse": "不利な",
    "affectionate": "愛情深い",
    "affordable": "手頃な",
    "ambiguous": "曖昧な",
    "ample": "十分な",
    "anonymous": "匿名の",
    "appreciative": "感謝した",
    "approximate": "おおよその",
    "arrogant": "傲慢な",
    "astonished": "驚いた",
    "astonishing": "驚くべき",
    "attached": "愛着のある",
    "attentive": "注意深い",
    "balanced": "バランスのとれた",
    "barren": "不毛な",
    "beneficial": "有益な",
    "benevolent": "慈悲深い",
    "biological": "生物学的な",
    "bizarre": "奇妙な",
    "breathtaking": "息をのむ",
    "breezy": "そよ風の",
    "burdensome": "重荷な",
    "bustling": "賑やかな",
    "carefree": "気楽な",
    "caring": "思いやりのある",
    "catastrophic": "壊滅的な",
    "charming": "魅力的な",
    "cherished": "大切にされた",
    "coherent": "一貫した",
    "compassionate": "思いやりのある",
    "compatible": "互換性のある",
    "competent": "有能な",
    "compulsory": "義務的な",
    "conceivable": "想像できる",
    "concrete": "具体的な",
    "constant": "一定の",
    "contemporary": "現代の",
    "contradictory": "矛盾した",
    "convenient": "便利な",
    "convincing": "説得力のある",
    "cooperative": "協力的な",
    "corrupt": "腐敗した",
    "costly": "費用のかかる",
    "courageous": "勇気のある",
    "creative": "創造的な",
    "crucial": "重要な",
    "cumulative": "累積的な",
    "cynical": "皮肉な",
    "decisive": "決断力のある",
    "dedicated": "専念した",
    "defective": "欠陥のある",
    "definitive": "決定的な",
    "deliberate": "意図的な",
    "demanding": "要求の多い",
    "dense": "密な",
    "depressed": "落ち込んだ",
    "derived": "派生した",
    "desirable": "望ましい",
    "determined": "決意した",
    "devoted": "献身的な",
    "distinctive": "特徴的な",
    "dominant": "支配的な",
    "doubtful": "疑わしい",
    "dynamic": "活動的な",
    "ecological": "生態学的な",
    "effective": "効果的な",
    "elaborate": "精巧な",
    "elderly": "高齢の",
    "eligible": "適格な",
    "eloquent": "雄弁な",
    "emotional": "感情的な",
    "enormous": "巨大な",
    "enthusiastic": "熱心な",
    "equivalent": "同等の",
    "ethical": "倫理的な",
    "exceptional": "例外的な",
    "excessive": "過度な",
    "exciting": "刺激的な",
    "exclusive": "独占的な",
    "explicit": "明確な",
    "explosive": "爆発的な",
    "extended": "拡張された",
    "extensive": "広範な",
    "faint": "かすかな",
    "faithful": "忠実な",
    "familiar": "親しみやすい",
    "fatal": "致命的な",
    "favorable": "好意的な",
    "fierce": "激しい",
    "flexible": "柔軟な",
    "fluent": "流暢な",
    "fortunate": "幸運な",
    "fragile": "壊れやすい",
    "fundamental": "基本的な",
    "genuine": "本物の",
    "gradual": "徐々の",
    "grateful": "感謝している",
    "greedy": "貪欲な",
    "harmful": "有害な",
    "harsh": "厳しい",
    "hazardous": "危険な",
    "helpless": "無力な",
    "heroic": "英雄的な",
    "hostile": "敵意のある",
    "ideal": "理想的な",
    "identical": "同一の",
    "ignorant": "無知な",
    "illegal": "違法な",
    "imaginative": "想像力豊かな",
    "immense": "巨大な",
    "implicit": "暗黙の",
    "inadequate": "不十分な",
    "incapable": "無能な",
    "inconsistent": "一貫性のない",
    "indispensable": "不可欠な",
    "influential": "影響力のある",
    "inherent": "固有の",
    "innovative": "革新的な",
    "insecure": "不安な",
    "inspiring": "感動的な",
    "intellectual": "知的な",
    "intentional": "意図的な",
    "intricate": "複雑な",
    "irreversible": "取り返しのつかない",
    "isolated": "孤立した",
    "keen": "鋭い",
    "legitimate": "合法的な",
    "lively": "活気のある",
    "logical": "論理的な",
    "mandatory": "義務的な",
    "mature": "成熟した",
    "meaningful": "意味のある",
    "meticulous": "几帳面な",
    "miserable": "惨めな",
    "moderate": "穏健な",
    "modest": "控えめな",
    "moral": "道徳的な",
    "motivated": "やる気のある",
    "mysterious": "神秘的な",
    "necessary": "必要な",
    "negative": "否定的な",
    "neutral": "中立の",
    "noble": "高貴な",
    "numerous": "多数の",
    "objective": "客観的な",
    "obsolete": "時代遅れの",
    "offensive": "不快な",
    "optimistic": "楽観的な",
    "optional": "任意の",
    "outstanding": "優れた",
    "overwhelming": "圧倒的な",
    "passionate": "情熱的な",
    "pessimistic": "悲観的な",
    "physical": "身体的な",
    "plentiful": "豊富な",
    "political": "政治的な",
    "potential": "可能性のある",
    "precise": "正確な",
    "predominant": "優勢な",
    "primitive": "原始的な",
    "privileged": "特権のある",
    "productive": "生産的な",
    "profound": "深い",
    "prominent": "著名な",
    "prosperous": "繁栄した",
    "provocative": "挑発的な",
    "qualified": "資格のある",
    "questionable": "疑わしい",
    "rational": "合理的な",
    "realistic": "現実的な",
    "rebellious": "反抗的な",
    "refined": "洗練された",
    "relevant": "関連のある",
    "reliable": "信頼できる",
    "reluctant": "気が進まない",
    "remarkable": "注目すべき",
    "renewable": "再生可能な",
    "resentful": "憤慨した",
    "resistant": "抵抗力のある",
    "responsible": "責任のある",
    "rigid": "固い",
    "ruthless": "冷酷な",
    "sacred": "神聖な",
    "sensitive": "敏感な",
    "significant": "重要な",
    "sophisticated": "洗練された",
    "stable": "安定した",
    "strategic": "戦略的な",
    "subjective": "主観的な",
    "substantial": "かなりの",
    "subtle": "微妙な",
    "superior": "優れた",
    "sustainable": "持続可能な",
    "symbolic": "象徴的な",
    "systematic": "系統的な",
    "tolerant": "寛容な",
    "transparent": "透明な",
    "tremendous": "莫大な",
    "trivial": "些細な",
    "typical": "典型的な",
    "uncertain": "不確かな",
    "uniform": "均一の",
    "universal": "普遍的な",
    "urgent": "緊急の",
    "valid": "有効な",
    "valuable": "価値のある",
    "vibrant": "活気のある",
    "violent": "暴力的な",
    "visible": "見える",
    "vital": "重要な",
    "voluntary": "自発的な",
    "vulnerable": "傷つきやすい",
    "widespread": "広まった",
    "worthy": "価値のある",
    # ── 形容詞 追加 ──────────────────────────────────────────────
    "adopted": "採用された",
    "ageless": "年齢を感じさせない",
    "attainable": "達成可能な",
    "atypical": "非典型的な",
    "authoritative": "権威のある",
    "bloody": "血まみれの",
    "boiling": "煮えたぎる",
    "bothered": "悩まされた",
    "bothersome": "煩わしい",
    "breakable": "壊れやすい",
    "chaotic": "混沌とした",
    "cheeky": "生意気な",
    "childish": "子供っぽい",
    "clumsy": "不器用な",
    "coarse": "粗い",
    "colonial": "植民地の",
    "communicative": "コミュニカティブな",
    "conventional": "慣習的な",
    "convinced": "確信した",
    "corporate": "企業の",
    "corresponding": "対応する",
    "cowardly": "臆病な",
    "creepy": "気持ち悪い",
    "dated": "時代遅れの",
    "decent": "まともな",
    "deceptive": "人を欺く",
    "decorative": "装飾的な",
    "dependable": "頼りになる",
    "detailed": "詳細な",
    "developing": "発展途上の",
    "dim": "薄暗い",
    "disorderly": "無秩序な",
    "dissatisfied": "不満な",
    "distinguished": "著名な",
    "distressing": "悲惨な",
    "domestic": "国内の",
    "dreadful": "ひどい",
    "dumb": "ばかな",
    "economical": "経済的な",
    "ecstatic": "有頂天の",
    "educated": "教育を受けた",
    "elegant": "優雅な",
    "enduring": "持続する",
    "entertaining": "楽しい",
    "ethnic": "民族の",
    "evil": "邪悪な",
    "executive": "幹部の",
    "exhausting": "疲れさせる",
    "exotic": "エキゾチックな",
    "expressive": "表現豊かな",
    "exquisite": "精巧な",
    "external": "外部の",
    "fabulous": "素晴らしい",
    "fascinated": "魅了された",
    "faulty": "欠陥のある",
    "fearsome": "恐ろしい",
    "federal": "連邦の",
    "fictional": "架空の",
    "fiscal": "財政的な",
    "fixed": "固定された",
    "flawless": "完璧な",
    "fluid": "流動的な",
    "formidable": "手ごわい",
    "foul": "ひどい",
    "frugal": "倹約的な",
    "functional": "機能的な",
    "furious": "激怒した",
    "gloomy": "暗い",
    "governmental": "政府の",
    "grand": "壮大な",
    "grim": "厳しい",
    "harmless": "無害な",
    "heartbreaking": "胸が張り裂けるような",
    "hilarious": "非常に面白い",
    "hollow": "空洞の",
    "hospitable": "温かくもてなす",
    "humble": "謙虚な",
    "humiliating": "屈辱的な",
    "hybrid": "ハイブリッドの",
    "icy": "氷のような",
    "idle": "怠惰な",
    "immoral": "不道徳な",
    "immortal": "不死の",
    "impartial": "公平な",
    "impolite": "失礼な",
    "impulsive": "衝動的な",
    "inaccurate": "不正確な",
    "incurable": "不治の",
    "indifferent": "無関心な",
    "indulgent": "甘やかす",
    "infectious": "感染性の",
    "informal": "非公式の",
    "innate": "生まれつきの",
    "inseparable": "切り離せない",
    "inspirational": "刺激的な",
    "insufficient": "不十分な",
    "interactive": "インタラクティブな",
    "interpersonal": "対人の",
    "intimate": "親密な",
    "invisible": "見えない",
    "irrational": "不合理な",
    "irresistible": "抵抗できない",
    "irresponsible": "無責任な",
    "irritated": "苛立った",
    "irritating": "苛立たせる",
    "legendary": "伝説的な",
    "legislative": "立法の",
    "lengthy": "長い",
    "liberal": "自由な",
    "literal": "文字通りの",
    "lousy": "ひどい",
    "lucrative": "儲かる",
    "luxurious": "豪華な",
    "manual": "手動の",
    "mediocre": "平凡な",
    "mighty": "強力な",
    "misleading": "誤解を招く",
    "moody": "気まぐれな",
    "mortal": "死すべき",
    "mournful": "悲しい",
    "moving": "感動的な",
    "multiple": "複数の",
    "nationwide": "全国的な",
    "naughty": "いたずらな",
    "neat": "きちんとした",
    "needless": "不必要な",
    "obedient": "従順な",
    "obsessive": "強迫的な",
    "odd": "奇妙な",
    "outrageous": "言語道断な",
    "overall": "全体的な",
    "overseas": "海外の",
    "pandemic": "パンデミックの",
    "particular": "特定の",
    "patriotic": "愛国的な",
    "persistent": "粘り強い",
    "petty": "些細な",
    "philosophical": "哲学的な",
    "picturesque": "絵のように美しい",
    "pointless": "無意味な",
    "potent": "強力な",
    "predictable": "予測可能な",
    "preferable": "望ましい",
    "prestigious": "権威のある",
    "preventive": "予防的な",
    "priceless": "非常に貴重な",
    "primary": "主要な",
    "prior": "優先の",
    "profitable": "利益の出る",
    "prompt": "迅速な",
    "punctual": "時間に正確な",
    "purposeful": "目的を持った",
    "puzzled": "困惑した",
    "rash": "無謀な",
    "redundant": "不必要な",
    "reflective": "内省的な",
    "relieved": "安心した",
    "resonant": "共鳴する",
    "respiratory": "呼吸の",
    "revolutionary": "革命的な",
    "risky": "危険な",
    "rural": "田舎の",
    "salty": "塩辛い",
    "satisfactory": "満足のいく",
    "seasonal": "季節の",
    "secondary": "二次的な",
    "selfless": "利他的な",
    "sensible": "賢明な",
    "serene": "穏やかな",
    "shabby": "みすぼらしい",
    "shaky": "震えている",
    "simultaneous": "同時の",
    "sincere": "誠実な",
    "skilled": "熟練した",
    "slight": "わずかな",
    "sloppy": "だらしない",
    "sociable": "社交的な",
    "solar": "太陽の",
    "sound": "健全な",
    "sparkling": "輝く",
    "stern": "厳格な",
    "stiff": "固い",
    "stingy": "けちな",
    "straightforward": "率直な",
    "striking": "印象的な",
    "successive": "連続の",
    "superb": "素晴らしい",
    "suspicious": "疑わしい",
    "swift": "素早い",
    "sympathetic": "同情的な",
    "tame": "飼いならされた",
    "technical": "技術的な",
    "tender": "優しい",
    "terrifying": "恐ろしい",
    "thoughtful": "思慮深い",
    "thrilling": "スリリングな",
    "timeless": "時代を超えた",
    "tiresome": "飽き飽きする",
    "tough": "強い",
    "toxic": "有毒な",
    "tricky": "巧妙な",
    "troublesome": "厄介な",
    "turbulent": "激動の",
    "twisted": "ねじれた",
    "ultimate": "究極の",
    "unacceptable": "受け入れられない",
    "unbearable": "耐えられない",
    "uncommon": "珍しい",
    "unconscious": "無意識の",
    "understandable": "理解できる",
    "unfamiliar": "不慣れな",
    "unforeseen": "予期しない",
    "united": "団結した",
    "unlimited": "無制限の",
    "unofficial": "非公式の",
    "unpopular": "不人気な",
    "unrealistic": "非現実的な",
    "unreasonable": "不合理な",
    "unreliable": "信頼できない",
    "unsafe": "安全でない",
    "unsatisfactory": "不満足な",
    "unsuccessful": "失敗した",
    "unsuitable": "不適切な",
    "unwilling": "嫌がる",
    "urban": "都市の",
    "vacant": "空の",
    "vigorous": "精力的な",
    "waterproof": "防水の",
    "wealthy": "裕福な",
    "weary": "疲れた",
    "western": "西の",
    "willing": "喜んで",
    "winding": "曲がりくねった",
    "witty": "機知のある",
    "worldwide": "世界的な",
    "worrying": "心配な",
    "worthless": "価値のない",
    "youthful": "若々しい",
    "yummy": "美味しい",
    # ── 副詞 ────────────────────────────────────────────────────
    "abnormally": "異常に",
    "abruptly": "突然に",
    "accordingly": "それに応じて",
    "actively": "積極的に",
    "additionally": "さらに",
    "adequately": "十分に",
    "aggressively": "積極的に",
    "alternatively": "代わりに",
    "amazingly": "驚くほど",
    "appropriately": "適切に",
    "artificially": "人工的に",
    "attentively": "注意深く",
    "bitterly": "激しく",
    "brilliantly": "見事に",
    "broadly": "広く",
    "calmly": "穏やかに",
    "casually": "気楽に",
    "cheerfully": "陽気に",
    "comfortably": "快適に",
    "confidently": "自信を持って",
    "considerably": "かなり",
    "conveniently": "便利に",
    "creatively": "創造的に",
    "critically": "批判的に",
    "cruelly": "残酷に",
    "culturally": "文化的に",
    "deliberately": "意図的に",
    "delicately": "繊細に",
    "densely": "密に",
    "desperately": "必死に",
    "dramatically": "劇的に",
    "efficiently": "効率的に",
    "emotionally": "感情的に",
    "enormously": "非常に",
    "enthusiastically": "熱心に",
    "equally": "等しく",
    "essentially": "本質的に",
    "eventually": "最終的に",
    "evidently": "明らかに",
    "exclusively": "もっぱら",
    "extensively": "広範に",
    "extraordinarily": "並外れて",
    "firmly": "しっかりと",
    "formally": "正式に",
    "fortunately": "幸運にも",
    "gradually": "徐々に",
    "honestly": "正直に",
    "ideally": "理想的に",
    "immediately": "すぐに",
    "independently": "独立して",
    "inevitably": "必然的に",
    "initially": "最初に",
    "intentionally": "意図的に",
    "largely": "主に",
    "legally": "合法的に",
    "locally": "地域的に",
    "logically": "論理的に",
    "morally": "道徳的に",
    "naturally": "自然に",
    "necessarily": "必ず",
    "negatively": "否定的に",
    "normally": "普通に",
    "obviously": "明らかに",
    "officially": "公式に",
    "originally": "元々",
    "partly": "部分的に",
    "passionately": "情熱的に",
    "peacefully": "平和的に",
    "physically": "身体的に",
    "politically": "政治的に",
    "positively": "肯定的に",
    "potentially": "潜在的に",
    "precisely": "正確に",
    "primarily": "主に",
    "privately": "個人的に",
    "professionally": "専門的に",
    "properly": "適切に",
    "rapidly": "急速に",
    "realistically": "現実的に",
    "reasonably": "合理的に",
    "relatively": "比較的に",
    "reliably": "確実に",
    "repeatedly": "繰り返して",
    "roughly": "おおよそ",
    "selectively": "選択的に",
    "seriously": "真剣に",
    "significantly": "著しく",
    "simultaneously": "同時に",
    "specifically": "具体的に",
    "steadily": "着実に",
    "strongly": "強く",
    "substantially": "かなり",
    "successfully": "うまく",
    "technically": "技術的に",
    "thoroughly": "徹底的に",
    "traditionally": "伝統的に",
    "ultimately": "最終的に",
    "uniformly": "均一に",
    "universally": "普遍的に",
    "virtually": "事実上",
    "voluntarily": "自発的に",
    "widely": "広く",
    "admiringly": "称賛して",
    "admittedly": "確かに",
    "adversely": "不利に",
    "affectionately": "愛情を込めて",
    "blindly": "盲目的に",
    "conversely": "逆に",
    "crossly": "怒って",
    "dearly": "深く",
    "doubly": "二重に",
    "eagerly": "熱心に",
    "elegantly": "優雅に",
    "emphatically": "強調して",
    "endlessly": "果てしなく",
    "exceptionally": "例外的に",
    "fantastically": "素晴らしく",
    "financially": "財政的に",
    "firstly": "まず第一に",
    "flexibly": "柔軟に",
    "fondly": "愛情を持って",
    "foolishly": "愚かにも",
    "forcefully": "力強く",
    "formerly": "以前は",
    "frankly": "率直に",
    "frantically": "気が狂ったように",
    "furiously": "激しく",
    "generously": "寛大に",
    "genuinely": "本当に",
    "globally": "世界的に",
    "hastily": "急いで",
    "hugely": "非常に",
    "impatiently": "苛立って",
    "innocently": "無邪気に",
    "invariably": "常に",
    "ironically": "皮肉にも",
    "jealously": "嫉妬して",
    "lastly": "最後に",
    "leisurely": "ゆっくりと",
    "likewise": "同様に",
    "literally": "文字通り",
    "loosely": "緩く",
    "momentarily": "一瞬",
    "narrowly": "かろうじて",
    "nervously": "緊張して",
    "openly": "公然と",
    "overly": "過度に",
    "patiently": "辛抱強く",
    "powerfully": "力強く",
    "preferably": "できれば",
    "presumably": "おそらく",
    "promptly": "すぐに",
    "proudly": "誇りを持って",
    "radically": "根本的に",
    "readily": "すぐに",
    "regardless": "かかわらず",
    "regrettably": "残念ながら",
    "rightly": "正しく",
    "scarcely": "ほとんど〜ない",
    "scientifically": "科学的に",
    "secondly": "第二に",
    "seldom": "めったに〜ない",
    "separately": "別々に",
    "sharply": "鋭く",
    "somewhat": "いくらか",
    "strictly": "厳しく",
    "stubbornly": "頑固に",
    "sufficiently": "十分に",
    "suitably": "適切に",
    "suspiciously": "疑わしそうに",
    "temporarily": "一時的に",
    "tenderly": "優しく",
    "thereafter": "その後",
    "thirdly": "第三に",
    "tremendously": "非常に",
    "undoubtedly": "疑いなく",
    "urgently": "緊急に",
    "utterly": "完全に",
    "verbally": "言葉で",
    "vigorously": "精力的に",
    "visibly": "目に見えて",
    "weakly": "弱く",
    "willingly": "喜んで",
    "wrongly": "間違って",
}

# ── CEFR-J → アプリ設定 ────────────────────────────────────────

CORE_TO_THEME = {
    "Animals": "nature", "Food and drink": "nature",
    "Plants and environment": "nature", "Weather and climate": "nature",
    "Colour and shape": "nature", "Natural features": "nature",
    "Body and health": "daily", "The home": "daily",
    "Time": "daily", "Physical description": "daily", "Clothes": "daily",
    "Education": "people", "Work and Jobs": "people",
    "Family and friends": "people", "Society": "people",
    "Sport and leisure": "people", "Entertainment": "people",
    "Travel and transport": "place", "Places and buildings": "place",
    "Geography and environment": "place",
    "Feelings and opinions": "mind", "Personality and character": "mind",
    "Thoughts and thinking": "mind",
    "Language and communication": "general",
    "Numbers and quantity": "general", "Technology": "general",
}

CEFR_POS_TO_APP = {
    "noun": "noun", "verb": "verb", "adjective": "adjective",
    "adverb": "adverb", "preposition": "preposition", "conjunction": "conjunction",
    "determiner": "conjunction", "pronoun": "noun",
    "number": "noun", "interjection": "general",
}

EXCLUDE = [
    re.compile(r"^[a-z]\.$"), re.compile(r"[/\.\-]"),
    re.compile(r"\s"), re.compile(r"'"),
]
FUNCTION_WORDS = {
    "a", "an", "the", "is", "are", "was", "were", "be", "been", "being",
    "have", "has", "had", "do", "does", "did", "will", "would", "could",
    "should", "may", "might", "shall", "can", "must", "not", "very",
    "all", "both", "each", "any", "some", "no", "this", "that", "these",
    "those", "i", "you", "he", "she", "it", "we", "they", "who", "which",
    "what", "when", "where", "why", "how", "and", "or", "but", "so", "if",
    "then", "my", "your", "his", "her", "its", "our", "their",
    "me", "him", "us", "them",
}


def is_excluded(word: str) -> bool:
    if word.lower() in FUNCTION_WORDS:
        return True
    return any(p.search(word) for p in EXCLUDE)


def infer_theme(core_inv: str, pos: str) -> str:
    if pos == "verb":
        return "action"
    if pos == "adjective" and "Feeling" in core_inv:
        return "mind"
    return CORE_TO_THEME.get(core_inv, "general")


def main() -> None:
    out_path = sys.argv[1] if len(sys.argv) > 1 else "tools/draft_eiken2_additional.csv"

    with open("assets/quiz/words.csv", newline="", encoding="utf-8") as f:
        rows = list(csv.DictReader(f))

    upper_words = {
        r["en"].lower() for r in rows
        if r["level"] in ("eiken5", "eiken4", "eiken3", "eiken_pre2")
    }
    eiken2_existing = [r for r in rows if r["level"] == "eiken2"]
    eiken2_kept = [r for r in eiken2_existing if r["en"].lower() not in upper_words]
    all_existing = {r["en"].lower() for r in rows}

    target = 1500
    need = target - len(eiken2_kept)
    print(f"重複削除後 eiken2: {len(eiken2_kept)}語")
    print(f"追加必要数: {need}語")

    with open("tools/data/cefrj.csv", newline="", encoding="utf-8") as f:
        cefrj = list(csv.DictReader(f))

    additions: list[dict] = []
    seen: set[str] = set()

    for row in cefrj:
        if row.get("CEFR", "").strip() != "B2":
            continue
        word = row.get("headword", "").strip()
        key = word.lower()
        if not word or key in all_existing or key in seen:
            continue
        if is_excluded(word):
            continue
        if key not in TRANSLATIONS:
            continue
        seen.add(key)
        cefr_pos = row.get("pos", "").strip().lower()
        app_pos = CEFR_POS_TO_APP.get(cefr_pos, "noun")
        if app_pos in ("preposition", "conjunction", "general"):
            continue
        core_inv = row.get("CoreInventory", "").strip()
        additions.append({
            "en": word,
            "ja": TRANSLATIONS[key],
            "pos": app_pos,
            "theme": infer_theme(core_inv, app_pos),
            "level": "eiken2",
        })

    additions = additions[:need]
    pos_counts = Counter(r["pos"] for r in additions)
    print(f"選出: {len(additions)}語 {dict(sorted(pos_counts.items()))}")

    with open(out_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(
            f, fieldnames=["id", "en", "ja", "pos", "theme", "level", "notes"],
        )
        writer.writeheader()
        for i, r in enumerate(additions, start=1):
            writer.writerow({
                "id": i, "en": r["en"], "ja": r["ja"],
                "pos": r["pos"], "theme": r["theme"],
                "level": "eiken2", "notes": "",
            })

    print(f"\n✅ 下書き生成: {len(additions)}語 → {out_path}")
    print(f"   eiken2 既存(重複削除後): {len(eiken2_kept)}語")
    print(f"   追加後の合計: {len(eiken2_kept) + len(additions)}語")


if __name__ == "__main__":
    main()
